### ISSUE TITLE
[QUESTION] GCHP v13.0.2 - CO and NOx emissions non zero in level 72 (GCHP.Emissions.YYYYMMDD_hhmmss.nc4)

### ISSUE THREAD

**Issue by mtsivlidou** [geoschem/GCHP#108]
Hello, 
I use GCHP v 13.0.2 (with intel/18.2 and openmpi/3.0.2) for monthly simulation. I noticed that the CO_total and NO_total emissions in GCHP.Emissions.19970116_1200z.nc4 are close to zero for all the levels except for the last one (72nd).
I would like to ask whether you have any idea why the levels are reversed for the emissions. 
(I use the default settings for the run taking into account CEDS for anthropogenic emissions). 

Thank you in advance, 
Maria

**Comment by LiamBindle** [comment]
Hi @mtsivlidou. Yeah the emissions collection is positive="down" which is the opposite of all other collections. This means that all 3D fields will be upside-down relative to 3D fields in other collections. I don't know specifically why this is the way it is though&mdash;@lizziel or @sdeastham, do you?

**Comment by sdeastham** [comment]
That's right! I would reverse the framing though - GEOS-Chem is weird in that it artificially flips all of its diagnostic fields to have 1=surface, rather than 1=TOA. I believe that most of the other components in the GEOS ecosystem use the standard of 1=TOA, including FV3, MAPL, and (evident here) HEMCO. Ideally we would follow that convention too, but it would be too disruptive to change all the internals of GEOS-Chem at this point (or at least, that was the decision when first building GCHP!) so instead we flip fields when entering or leaving the "chemistry" component.

**Comment by mtsivlidou** [comment]
Hello, 
Thank you for your answers. 
The Species concentration collection is also positive down but judging from the global maps of O3 and CO, I would say level 1 is surface and level 30 is stratosphere. Do you have any idea why this happens?
Also, I use the gcpy.file_regrid function to regrid in latlon grid and the model levels 1,2,3.. are converted to 1000...0.  In that case the CO profile is reversed again, but I need to see how the regrid function works in detail.

**Comment by LiamBindle** [comment]
Thanks for the correction. I meant the indexes are usually 0 for surface and 71 for TOA in the diagnostics, but reversed for the emissions collection. The `lev` coordinate's values aren't changed though. I believe it's because we just reverse the `lev` coordinate.

In [gcpy.file_regrid](https://github.com/geoschem/gcpy/blob/main/gcpy/file_regrid.py#L153) I see a couple places where the vertical coordinate is getting flipped. @WilliamDowns can you explain the behaviour?

Recently I put together a regridding workflow that is more robust, flexible, and faster than gcpy.file_regrid: [here](https://github.com/LiamBindle/sparselt). The [`examples/`](https://github.com/LiamBindle/sparselt/tree/master/examples) subdirectory has an example of regridding C48 to a lat-lon grid. Here is what it looks like: [see here](https://github.com/LiamBindle/sparselt#applying-esmf-regrid-weights). It's fully compatible with cubed-sphere/stretched-grid/lat-lon conversion and ~all~ *some more* ESMF regridding methods. It is also easy to port to other languages (e.g., Matlab) because it's just a sparse matrix multiplication. I recommend this new workflow rather than gcpy.file_regrid, unless you need to create restart files.

**Comment by mtsivlidou** [comment]
Thanks. I tried your method, it is working for the gchp13_sample_species.nc (https://github.com/LiamBindle/sparselt/blob/master/examples/sample_data/gchp13_sample_species.nc) but not for my file. The error I get is:
ValueError: operand to apply_ufunc has required core dimensions ['nf', 'Ydim', 'Xdim'], but some of these dimensions are absent on an input variable: ['nf', 'Ydim', 'Xdim']
I think the problem is that in my nc file includes :
char cubed_sphere ;
                cubed_sphere:additional_vars = "contacts,orientation,anchor" ;
                cubed_sphere:file_format_version = "2.90" ;
                cubed_sphere:grid_mapping_name = "gnomonic cubed-sphere" ;
                cubed_sphere:gridspec_file = "gridspec.nc4" ;

I tried with nco to select concrete variables (similar to your gchp13_sample_species.nc) but it does not exclude the cubed_sphere. 
Thank you again!

**Comment by WilliamDowns** [comment]
> 
> In [gcpy.file_regrid](https://github.com/geoschem/gcpy/blob/main/gcpy/file_regrid.py#L153) I see a couple places where the vertical coordinate is getting flipped. @WilliamDowns can you explain the behaviour?
> 

The vertical coordinates are currently automatically flipped in all CS <-> LL transformations (and replaced with 1...72 or 1000...0) because they are intended to match the coordinate setup of the equivalent GC Classic or GCHP file. All collections for GCHP are 1=TOA as far as I can tell, whereas all collections for GC Classic (including HEMCO output) are 1=surface. Correct me if I'm wrong.

EDIT: Disregard this. There is a `positive: down` attribute in all GCHP diagnostics that suggests all collections are 1=TOA, but this attribute is actually incorrect for most collections.

**Comment by lizziel** [comment]
The emissions collection should not be flipped. It is currently 72=TOA, as is the restart file.

**Comment by LiamBindle** [comment]
> Thanks. I tried your method, it is working for the gchp13_sample_species.nc (https://github.com/LiamBindle/sparselt/blob/master/examples/sample_data/gchp13_sample_species.nc) but not for my file. The error I get is:
> ValueError: operand to apply_ufunc has required core dimensions ['nf', 'Ydim', 'Xdim'], but some of these dimensions are absent on an input variable: ['nf', 'Ydim', 'Xdim']
> I think the problem is that in my nc file includes :
> char cubed_sphere ;
> cubed_sphere:additional_vars = "contacts,orientation,anchor" ;
> cubed_sphere:file_format_version = "2.90" ;
> cubed_sphere:grid_mapping_name = "gnomonic cubed-sphere" ;
> cubed_sphere:gridspec_file = "gridspec.nc4" ;
> 
> I tried with nco to select concrete variables (similar to your gchp13_sample_species.nc) but it does not exclude the cubed_sphere.
> Thank you again!

Sorry, I forgot to mention that. The variables in the dataset passed to `sparselt.xr.transform()` need the same coordinates as the `input_dims` in your transformer object. You can drop that `cubed_sphere` variable like so
```python
ds = ds.drop('cubed_sphere')             # drop variables without ('nf' 'Ydim', 'Xdim') coordinates
ds = sparselt.xr.apply(transform, ds)
```
The documentation for `xarray.Dataset.drop()` can be found [here](http://xarray.pydata.org/en/v0.18.2/generated/xarray.Dataset.drop.html).

**Comment by mtsivlidou** [comment]
Hello, I plotted SPC O3 for 3 model levels (2, 42 and 72)  based on the gcchem_internal_checkpoint restart. 
Do you have any idea what can cause the reversed levels in the emissions collection or why the restart file looks like this (the simulation is supposed to be global!)?
Thank you,
Maria

![SPC_O3_lev_2in_gcchem_internal_checkpoint restart 1997020](https://user-images.githubusercontent.com/71709317/122410478-3fec1000-cf84-11eb-81f4-a2557145b7aa.png)
![SPC_O3_lev_42in_gcchem_internal_checkpoint restart 1997020](https://user-images.githubusercontent.com/71709317/122410482-4084a680-cf84-11eb-909a-4daa42737238.png)
![SPC_O3_lev_72in_gcchem_internal_checkpoint restart 1997020](https://user-images.githubusercontent.com/71709317/122410488-411d3d00-cf84-11eb-88bf-7903dd95afd8.png)

**Comment by lizziel** [comment]
Hi Maria, it looks like you are viewing the restart file using Panoply. That program does not correctly plot cubed sphere data and displays a subset of the data on a small region of the globe. This is not the case for history diagnostic collection files. We hope that eventually MAPL is updated so that checkpoint files have the same format as the history diagnostics so that they are viewable with Panoply. Until that happens you will need to either reformat the file, regrid to lat-lon, or plot cubed-sphere data using different software such as python package GCPy.

As discussed earlier in this thread, level 1 corresponds to top-of-atmosphere for checkpoint (restart) files and the HEMCO emissions (Emissions collection). Level 1 corresponds to surface for all other output. This is discussed on the [GCHP Output Data wiki page](http://wiki.seas.harvard.edu/geos-chem/index.php/GCHP_Output_Data) which I am just noticing now was not ported to [ReadTheDocs](https://readthedocs.org/projects/gchp/). We will expand the new documentation to include this information.

The inclusion of the "positive" attribute for level in output files is a relatively recent addition to MAPL. MAPL assigns value of "down" by default since this is what is done in GEOS for which MAPL is written. Thank you for pointing out its presence in the files since we did not add code to GCHP to manually change it to "up" for restart files and Emissions collection. This will be a bug fix we will add in the future.
