### ISSUE TITLE
[BUG/ISSUE] GCHP v 13.0.2 breaks while doing LINOZ

### ISSUE THREAD

**Issue by mtsivlidou** [geoschem/GCHP#114]
### Description of the problem
I am using GCHP v 13.0.2 for monthly simulations starting 19970101 000000. 
The simulation for the month 19970901 breaks while doing LINOZ. 

pe=00070 FAIL at line=00232    FileMetadata.F90                         <can not find time>
pe=00070 FAIL at line=00083    FileMetadataUtilities.F90                <status=1>
pe=00070 FAIL at line=02777    MAPL_ExtDataGridCompMod.F90              <status=1>
pe=00070 FAIL at line=01512    MAPL_ExtDataGridCompMod.F90              <status=1>
pe=00070 FAIL at line=01829    MAPL_Generic.F90                         <needs informative message>
pe=00070 FAIL at line=01066    MAPL_CapGridComp.F90                     <status=1>
pe=00070 FAIL at line=01013    MAPL_CapGridComp.F90                     <status=1>

I would appreciate it if you can help me solve my problem.
Thank you in advance, 
Maria

### GEOS-Chem version
GCHP v 13.0.2 

### Description of code modifications
No modification

### Log files
- Build log (if applicable): [CMakeOutput.log.txt](https://github.com/geoschem/GCHP/files/6786461/CMakeOutput.log.txt)
- Run log (if applicable):  [slurm-656000.out.txt](https://github.com/geoschem/GCHP/files/6786462/slurm-656000.out.txt) 
- [multirun.log.txt](https://github.com/geoschem/GCHP/files/6786468/multirun.log.txt)

- Run script (if applicable): 
[gchp.multirun.run.txt](https://github.com/geoschem/GCHP/files/6786464/gchp.multirun.run.txt)
[gchp.multirun.sh.txt](https://github.com/geoschem/GCHP/files/6786465/gchp.multirun.sh.txt)
[runConfig.sh.txt](https://github.com/geoschem/GCHP/files/6786467/runConfig.sh.txt)

[gchp.env.txt](https://github.com/geoschem/GCHP/files/6786470/gchp.env.txt)

### Software versions
- Compilers (Intel or GNU, and version): intel/18.2
- NetCDF version:  netcdf/4.7.3-openmpi 
- MPI version: openmpi/icc/3.0.2
- ESMF version: 8.0.1
hdf5/1.10.2-openmpi
cmake/3.13.0

**Comment by lizziel** [comment]
Hi @mtsivlidou, from the slurm log file it looks like the error is occurring fairly far into the run, when it hits hour 23:00 on Sept 24th. 
```
 AGCM Date: 1997/09/24  Time: 23:00:00  Throughput(days/day)[Avg Tot Run]:  138.9  421.9  427.6  TimeRemaining(Est) 001:02:38   14.9% :  12.6% Mem Comm:Used
                                                                      Mem/Swap Used (MB) at MAPL_Cap:TimeLoop=  2.826E+04  0.000E+00
pe=00001 FAIL at line=00245    NetCDF4_FileFormatter.F90                <status=-101>
pe=00001 FAIL at line=00090    MAPL_ExtDataCollection.F90               <status=-101>
pe=00001 FAIL at line=00232    FileMetadata.F90                         <can not find time>
```

The traceback points to MAPL ExtData which indicates this may be an input file issue. Could you try rerunning with the MAPL ExtData debug prints on? This is a switch you configure in runConfig.sh (search for 'debug'). Since enabling ExtData prints will greatly slow down the model and make your log excessively large, best do a single segment run starting on 9/24. See if it encounters the same error. If it does, there should be more info in the log to determine what file is being read when it happens.

**Comment by mtsivlidou** [comment]
Hello,
Thank you for the suggestions. Yes I can do that.
I was searching in GeosCore/linoz_mod.f to find the input files that it reads in this step but I didnt find anything. Is there any way to get such information? 
Maria

**Comment by mtsivlidou** [comment]
Hello, 
Thank you for your suggestion. I found the missing file:
 /HcoDir/OFFLINE_SEASALT/v2019-01/0.5x0.625/%y4/%m2/seasalt_05.%y4%m2%d2.nc 

I would like to ask you another question. My simulation starts 199701 and it will be 10-20 years. 
With the debug for 199709, I realised that in the dir /HcoDir/OFFLINE_SEASALT/v2019-01/0.5x0.625/ the YYYY subfolders are empty, except for the year 2016. As a result, in my previous runs -Jan to Sept 1997- the input for OFFLINE_SEASALT was from 2016 and not from 1997.
Is it normal the model to take into account input from 2016 and not from the simulation date? 
Maria 

[gchp.log.txt](https://github.com/geoschem/GCHP/files/6791656/gchp.log.txt)

**Comment by lizziel** [comment]
Hi Maria, if input data is not available for a given year then GCHP will use the nearest available year. That being said, the offline seasalt inventory should have data for 1980-2019. Have you tried a fresh download of it? I believe Compute Canana is having issues lately but we also have it available on the [Harvard ftp site](http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/OFFLINE_SEASALT/v2019-01/).

**Comment by mtsivlidou** [comment]
Hello, 
I am sorry to bother you again. I use the model in another cluster, and I have a similar error there. From the log file there is no indication about the missing file though. I compared the ExtData dir in both clusters and I dont see anything missing in the second one. I would like to kindly ask you whether you have any idea what might cause the error. 
Thank you in advance, 
Maria


[slurm-12060473.out.txt](https://github.com/geoschem/GCHP/files/6809957/slurm-12060473.out.txt)
[HEMCO.log.txt](https://github.com/geoschem/GCHP/files/6809958/HEMCO.log.txt)
[gchp-13.0.2-cines-test-openmpi-4.1.1-12060388.log.txt](https://github.com/geoschem/GCHP/files/6809959/gchp-13.0.2-cines-test-openmpi-4.1.1-12060388.log.txt)

**Comment by lizziel** [comment]
Hmm, this is puzzling. I will see if I can reproduce on my cluster for the same run (13.0.2, 1-hr C48 fullchem simulation starting Jan 1 1998 00:00:00).

**Comment by mtsivlidou** [comment]
I have tried it for several random dates from 1995-2015 and it always gives that error (after the same MEGAN file in the log).
It might be a file that does not change for the different dates
I compared the size of each ExtData folder versus the other cluster (where GCHP s working), and I dont see any difference. 
Do you think it might be related to the compilation of the model and not with an input file?
Maria

**Comment by lizziel** [comment]
Hi Maria, I have not been able to reproduce the issue. I don't think it is a compilation problem since the error message indicates it is a file time error. Looking at the your error message and comparing it with my 13.0.2 run directory I see that you are using a non-standard MEGAN file. The default is 0.25x0.6125, but you are using 2x2.5 file. If you do ncdump -h on the file what do you see for the time variable?

**Comment by mtsivlidou** [comment]
Hello, 
I found the issue. 
I used the change_met.sh script (http://wiki.seas.harvard.edu/geos-chem/index.php/Running_GCHP:_Configuration_v12#Inputs). 
After running the line # For GEOS-FP
sed -i "s/025x03125\.nc/2x25.nc/g" ExtData.rc 
the path in ExtData.rc pointing to the standard MEGAN file changed to 2x25 file. 
Thanks a lot!
Maria

**Comment by lizziel** [comment]
Hi Maria, thanks for following up about what the issue was. The documentation where the `change_met.sh` script is available is for version 12 only. Documentation for version 13 is now on [ReadTheDocs](https://gchp.readthedocs.io/en/latest/) rather than the wiki and excludes using that script for changing meteorology. Changing the met should be done during the run directory creation step instead.

**Comment by mtsivlidou** [comment]
Hello, could you please give more details about this change? I have been through the documentation of the new version, but I have not found anything about changing the met. Thank you in advance.

**Comment by lizziel** [comment]
Of course! When you create a run directory one of the options you must choose is meteorology source. See https://gchp.readthedocs.io/en/latest/user-guide/rundir-init.html. If you already have a run directory but with a different meteorology source than you want to use then you should create a new one.

**Comment by lizziel** [comment]
Maria wrote:

> But is it possible to change the resolution of the met files while creating a run dir?
> I use MERRA2 files, but instead of the native resolution I was trying to switch to 2x2.5. Thats why I was using the change_met.sh:
> #!/bin/bash
> if [[ $# -ne 1 ]]; then
> echo "Must provide path to either GEOS_2x2.5/MERRA2 or GEOS_2x2.5/GEOSFP"
> exit 70
> fi
> if [[ -L MetDir ]]; then unlink MetDir; fi
> For MERRA-2
> sed -i "s/05x0625.nc/2x25.nc/g" ExtData.rc
> ln -s $1 MetDir
> exit 0

Sorry, I misunderstood what you were doing. We do not recommend using low resolution meteorology fields in GCHP, hence it is not an option during run directory creation. Are you using the low resolution because you do not have space for the high resolution files? 

If you must use low resolution files I recommend copying the original `ExtData.rc` config file as `ExtData.rc.orig` (or some other name), doing a search and replace within `ExtData.rc`, and then inspecting the difference from the original to make sure only the met of interest changed, and to the correct filenames and paths that you have.

**Comment by mtsivlidou** [comment]
I am not sure if there is enough memory to store the met files in native resolution. 
I swith to lower merra resolution to optimize the run time simulation and make it less computational expensive. The resolution of my simulation is 2x25.  The merra files shouldnt be interpolated to this resolution during the run?

**Comment by lizziel** [comment]
2x2.5 is indeed on par with C48, and would be regridded to C48 at run-time. We use C48 for benchmarking GCHP but in general I believe the GCHP Working Group recommends running GCHP at resolution C90 or higher for science runs.

I do not see your project listed on the [Working Group current GCHP projects list](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_High_Performance_Working_Group#Current_GCHP_Projects). I recommend adding it to the list and being in touch with the GCHP co-chairs about your research so they are aware. If there are any concerns with using low resolution met and run simulation for your purposes they would be able to let you know.
