### ISSUE TITLE
[BUG/ISSUE] No time dimension in TrashBurn_v2_generic.01x01.nc file for GCHP simulation with EDGAR turned on

### ISSUE THREAD

**Issue by 1Dandan** [geoschem/GCHP#124]
### Description of the problem
I am trying to run a GCHP simulation with EDGAR turned on. But the file of TrashBurn_v2_generic.01x01.nc under path of /ExtData/HEMCO/TrashEmis/v2015-03/TrashBurn_v2_generic.01x01.nc doesn't have the time dimension (showed below) but does have time variable. Also, the time in the Trash_emissions_readme.pdf and HEMCO_Config.rc are both 2008 but the time variable in the file is 1985. 
![image](https://user-images.githubusercontent.com/75513026/128766201-c67fb602-eed3-49f2-84d3-7bef409a36a3.png)

Trash_emissions_readme:
![image](https://user-images.githubusercontent.com/75513026/128766620-94696538-8d36-4db1-8a8b-e1d386dbd493.png)

HEMCO_Config:
![image](https://user-images.githubusercontent.com/75513026/128766840-f6b115eb-6aff-4b8d-9887-1f726d84f465.png)

### GEOS-Chem version
GCHP v13.0.0

### Description of code modifications
No modification in the source code but turned on EDGAR emission.

### Log files
- Build log (if applicable):
- Run log (if applicable): 
[SIM_START-20210809_1824.log](https://github.com/geoschem/GCHP/files/6957090/SIM_START-20210809_1824.log)

- Run script (if applicable):

### Software versions
- Compilers (Intel or GNU, and version): GNU 8.3.1
- NetCDF version: 4.7.3
- MPI version: OpenMPI 3.1.5
- ESMF version: 8.0.0

**Comment by lizziel** [comment]
Hi @1Dandan, thanks for reporting this. Could you do another run, just 1 hour, with the the MAPL debug print option turned on in `runConfig.sh`? This will print out more information about the problem to the log. It should be okay that the variables do not have a time dimensions since they are treated as time-invariant fields in config file `ExtData.rc`. The time information in `HEMCO_Config.rc` is ignored in GCHP. This makes me wonder if there is a problem with another file.

Another thing you can do is update to GCHP 13.1. This includes improved input error handling which may also help figure out the issue. Instructions for enabling the debug prints in that version are in `runConfig.sh` (same section as in 13.0) and the debug output is sent to new output file `allPEs.log`.

**Comment by 1Dandan** [comment]
Thanks @lizziel. Yes, you are right. The TrashEmis file is fine for running GCHP simulation. The reason why my simulation crashed is because I set the start time (20181201) at the exact time of the gcchem_internal_checkpoint_20181201_0000z.nc4 which can not be overwritten. Sorry. Thanks for your suggestions.

**Comment by lizziel** [comment]
Okay, glad you figured it out. Thanks for following up.
