### ISSUE TITLE
[QUESTION] GCHP run failed, HCO_Init & HCO_GC_Init errors?

### ISSUE THREAD

**Issue by clearsky112** [geoschem/GCHP#127]
I'm a new user. I tried to run gchp, but it stopped with the errors in GC.log:

==================================================
GEOS-Chem ERROR: Error encountered in "HCO_Init"!
 -> at HCOI_GC_Init (in module GeosCore/hco_interface_gc_mod.F90)

==================================================
GEOS-Chem ERROR: Error encountered in "HCOI_GC_Init"!
 -> at Emissions_Init (in module GeosCore/emissions_mod.F90)

 I did not find the HEMCO log. Can you help me solve this problem? Thanks.

**Comment by lizziel** [comment]
Hi @clearsky112, could you attach your log, run script, and config files? You can drag and drop them into the github comment box if renamed to end with '.txt'.

**Comment by clearsky112** [comment]
> Hi @clearsky112, could you attach your log, run script, and config files? You can drag and drop them into the github comment box if renamed to end with '.txt'.

Ok, pls find the files as below. Thank you again. 
[GC.txt.log](https://github.com/geoschem/GCHP/files/7002964/GC.txt.log)
[HEMCO_Config.txt.txt](https://github.com/geoschem/GCHP/files/7002965/HEMCO_Config.txt.txt)
[input.geos.txt.txt](https://github.com/geoschem/GCHP/files/7002966/input.geos.txt.txt)
[logfile.000000.out.txt.txt](https://github.com/geoschem/GCHP/files/7002967/logfile.000000.out.txt.txt)
[simple_batch_job.sh.txt.txt](https://github.com/geoschem/GCHP/files/7002968/simple_batch_job.sh.txt.txt)
[slurm-4405.out.txt.txt](https://github.com/geoschem/GCHP/files/7002969/slurm-4405.out.txt.txt)

**Comment by lizziel** [comment]
Hi @clearsky112, The problem you are seeing is in subroutine `HcoDiagn_Init` as indicated in the line directly above the error message you copied into your comment above. Try doing another run after setting `HEMCO_Config.rc` entries `Verbose` and `Warnings` to 3. This increases the number of messages printed from HEMCO to log. Since this is your first with GCHP I also recommend turning on the MAPL ExtData debug prints. Search for `Debug` in config file runConfig.sh for instructions on how to do this. The HEMCO_Config.rc change will likely give more information about the error you are encountering. The MAPL debug prints would give information on later input errors should you encounter any.

Hopefully that will shed some light on what is going on. Every now and then there is an unexpected error in HEMCO when running GCHP that does not get caught by the log prints, either because no error prints were implemented or because the prints are only done from the root processor which never had a chance to get to the problem location. Also if the error occurs early in the run during initialization then the `HEMCO.log` file may not have been initialized yet.

If you still run into an issue, please also upload your `ExtData.rc` and `HEMCO_Diagn.rc` config files, and let us know what version you are running.

**Comment by clearsky112** [comment]
Thanks. Maybe the error occurs early in the run, I changed the setting as your suggestions but still couldn't have HEMCO.log output to diagnose the issues. There might be issues to read ExtData.rc or read initial_GEOSchem* , but I don't know where the problem is. 

I git clone the gchp via https://github.com/geoschem/GCHP, the version is 13.0.2.

I attached all files here and hope could get your help. Thank you.

[archiveRun.sh.txt](https://github.com/geoschem/GCHP/files/7010274/archiveRun.sh.txt)
[CAP.rc.txt](https://github.com/geoschem/GCHP/files/7010275/CAP.rc.txt)
[cleanRunDir.sh.txt](https://github.com/geoschem/GCHP/files/7010276/cleanRunDir.sh.txt)
[ExtData.rc.txt](https://github.com/geoschem/GCHP/files/7010277/ExtData.rc.txt)
[GC.txt.log](https://github.com/geoschem/GCHP/files/7010278/GC.txt.log)
[GCHP.rc.txt](https://github.com/geoschem/GCHP/files/7010279/GCHP.rc.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/GCHP/files/7010281/HEMCO_Config.rc.txt)
[HEMCO_Diagn.rc.txt](https://github.com/geoschem/GCHP/files/7010282/HEMCO_Diagn.rc.txt)
[HISTORY.rc.txt](https://github.com/geoschem/GCHP/files/7010283/HISTORY.rc.txt)
[input.geos.txt](https://github.com/geoschem/GCHP/files/7010284/input.geos.txt)
[input.nml.txt](https://github.com/geoschem/GCHP/files/7010285/input.nml.txt)
[logfile.000000.out.txt](https://github.com/geoschem/GCHP/files/7010286/logfile.000000.out.txt)
[runConfig.sh.txt](https://github.com/geoschem/GCHP/files/7010287/runConfig.sh.txt)
[setEnvironment.sh.txt](https://github.com/geoschem/GCHP/files/7010288/setEnvironment.sh.txt)
[simple_batch_job.sh.txt](https://github.com/geoschem/GCHP/files/7010289/simple_batch_job.sh.txt)
[slurm-4518.out.txt](https://github.com/geoschem/GCHP/files/7010290/slurm-4518.out.txt)
[species_database.yml.txt](https://github.com/geoschem/GCHP/files/7010291/species_database.yml.txt)
[warnings_and_errors.txt.log](https://github.com/geoschem/GCHP/files/7010292/warnings_and_errors.txt.log)

**Comment by clearsky112** [comment]
Thanks. I only tested 1 hour, but in HEMCO_Config.rc, the default "DiagnFreq" was "Monthly". When I changed it to "End", it printed "HEMCO.log".

**Comment by lizziel** [comment]
Interesting. I had thought that field was not used in GCHP so this is really good information to have. Does your run still error out?

**Comment by clearsky112** [comment]
> Interesting. I had thought that field was not used in GCHP so this is really good information to have. Does your run still error out?

Yes, it gave errors, but all were just the missing HEMCO files. I downloaded them and GCHP is running now.  Thank you.

**Comment by lizziel** [comment]
Excellent. I am glad it is working now. I will create a GitHub issue in HEMCO about the DiagnFreq being set to Monthly by default, and how this may prevent creation of the HEMCO.log file if errors are encountered due to a missing file.
