### ISSUE TITLE
[BUG/ISSUE] runConfig.sh shouldn't prevent non-standard cubed-spheres, and stretched-grid simulations should use OFFLINE_DUST

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCHP#152]
### Description of the problem
If you try to use cubed-sphere size that isn't c24, c48, c90, c180, or c360 `runConfig.sh` throws the following error

```
Dust scale factor not defined for this resolution. Please add the tuning factor you wish to use for the target resolution above.
```

Stretched-grid simulations will typically use non-standard cubed-sphere sizes, and stretched-grid simulations should use OFFLINE_DUST anyway. To get around this error check I've been suggesting that people just delete this section of runConfig.sh, but really it should be fixed in runConfig.sh.

### GEOS-Chem version
13.0 and 13.1

**Comment by LiamBindle** [comment]
I propose the following handling:

1. If it's a stretched-grid simulation, throw a warning if OFFLINE_DUST is not `true` and DustDead is not `off`.
2. Throw the error in question iff DustDead is `on`.

@lizziel What do you think?

**Comment by lizziel** [comment]
**Update:** reread this if only read the original github notification since I had some online/offline switched.

That's odd, that error already should only be triggered if DustDead is `on` and so need the tuning factor. Is there something incorrect in the code for it?
```
#------------------------------------------------------------------                                           
#    Dust mass tuning factor (only if using HEMCO dust extension)                                             
#------------------------------------------------------------------                                           
dustEntry=$(grep "105.*DustDead" HEMCO_Config.rc)
dustSetting=(${dustEntry// / })
if [[ ${dustSetting[3]} = "on" ]]; then
    if [[ $CS_RES -eq 24 ]]; then
        Dust_SF=6.0e-4
    elif [[ $CS_RES -eq 48 ]]; then
        Dust_SF=5.0416e-4
    elif [[ $CS_RES -eq 90 ]]; then
        Dust_SF=4.0e-4
    elif [[ $CS_RES -eq 180 ]]; then
        Dust_SF=3.23e-4
    elif [[ $CS_RES -eq 360 ]]; then
        Dust_SF=2.35e-4
    elif [[ $CS_RES -eq 720 ]]; then
        Dust_SF=2.3e-4
    else
        echo "Dust scale factor not defined for this resolution. Please add the tuning factor you wish to use\
 for the target resolution above."
        exit 1
    fi
fi
```

If stretched grid should always have offline dust on / online dust off then perhaps it should be auto-set with a warning? Or if not auto-set and online dust is on, then stop the run with an error. It would be unfortunate if someone did a long run without being aware they should not have used online dust. At the same time, I'm wary of more auto-setting, and also disabling online dust completely from stretched grid runs. It may be useful to have it on for benchmark comparisons (we only have it on in GCHP for benchmark simulations, for better or worse). I'd toss the decision on what the handling should be for users regarding offline/online dust to @sdeastham.

**Comment by sdeastham** [comment]
Oof, that's a tough one. I don't think there's any sensible way to handle online dust + stretched grid. Online dust + a scaling factor is already a kludge for the different global resolutions, but at least makes a sort of sense because you're trying to compensate for the reduction in wind variability which is related to the size of the grid cells. Once you're using a stretched grid, that compensating factor would have to vary by location. Technically that's true for GC-Classic too, but since most of the dust is produced in the same latitudes (30-45 N/S), the scaling factor can be roughly constant. With the SG, the scaling factor would need to vary a great deal.

My suggestion would be to have runConfig.sh stop with an error if SG is used with online dust, rather than to change a setting. I'd leave it as an exercise to the reader to figure out a better online solution (implementation of the "HEMCO grid" in GCHP would be one such fix).

**EDIT**: to speak to Liam's other point, I also agree that a *warning* if `OFFLINE_DUST` is off + SG is on makes sense. That would give the behavior of:

SG is on:
* online dust on: error
* offline dust on: OK (as long as online dust is off) <-- preferred
* offline dust off: warning

SG is off:
* online dust on: OK (as long as a scaling factor is provided and offline dust is off)
* offline dust on: OK (as long as online dust is off) <-- preferred
* offline dust off: warning
