### ISSUE TITLE
[BUG/ISSUE] Timestamp of species concentration at 2300z not 0000z

### ISSUE THREAD

**Issue by xpye98** [geoschem/gchp#162]
### Description of the problem
I set the frequency and duration to be `010000` and `240000` to output hourly diagnostics in daily file, for both time-averaged and instantaneous collections.

However, the output SpeciesConc files (time-averaged) look like `GEOSChem.SpeciesConc.yyyymmdd_2300z.nc4` except the first day, which is right as `0000z.nc4`. In `yyyymmdd_2300z.nc4` file, the `time` variable starts from `yyyymmdd_2300` to `yyyymmdd+1_2200`. 

For ConcAboveSfc file (instantaneous), the files are right as `GEOSChem.ConcAboveSfc.yyyymmdd_0000z.nc4` except the first day, which is `0100z.nc4`.

I attach my `runConfig.sh` and `HISTORY.rc` behind.

I wonder if this is on purpose or there is something wrong with my settings?  
Thanks in advance!

### GEOS-Chem version
GCHP 13.2.0

### Description of code modifications
Describe your code modifications here.

### Log files

[HISTORY.rc.txt](https://github.com/geoschem/GCHP/files/7252679/HISTORY.rc.txt)
[runConfig.sh.txt](https://github.com/geoschem/GCHP/files/7252680/runConfig.sh.txt)

### Software versions
- Compilers (Intel or GNU, and version): gcc@9.3.0
- NetCDF version: netcdf-fortran@4.5.3
- MPI version: openmpi@4.1.1
- ESMF version: 8.0.1

**Comment by LiamBindle** [comment]
@xpye98 Thanks for opening this. Sorry for the delayed response, I was on vacation.

I think that this might be caused by the `timestampStart` field being `.true.`. This is a new field and I'm not familiar with it yet. It seems like a likely culprit since it's a new feature that affects the file name. Could you try setting it to `.false.`?

The default value for `ref_time` is `000000` so a 1-hour frequency should result in time-averages for 00:00:00/01:00:00, 01:00:00/02:00:00, ..., 23:00:00/24:00:00. I'm wondering if "timestampStart" has a bug since the 23:00:00/24:00:00 segment's start time is technically the previous day. If this is the case I'd suggest we omit "timestampStart" in the standard simulation's template and just use it in the benchmark simulation.

**Comment by xpye98** [comment]
I switch `timestampStart` to be `.false.`
But now the output files end like `yyyymmdd_2330z.nc4`, and time starts from `23:30:00` on `dd` to `22:30:00` on `dd+1`
So I guess `timestampStart` may just force the half hour to be integral?

**Comment by LiamBindle** [comment]
We talked about this in the GCHP-MAPL meeting earlier today. They confirmed that this is a bug. The MAPL developers are working on a fix (see this issue: https://github.com/GEOS-ESM/MAPL/issues/1064).

In the meantime, it should be okay to ignore (it appears to only affect the filename) - we will pull in the fix once it's ready. We can leave this issue open until then.

**Comment by LiamBindle** [comment]
Fixed in 46b52fa36b3a8520400ea4e24379b77928c84834. The fix will be included in 13.3.1.

Thanks for reporting this @xpye98!

**Comment by lizziel** [comment]
This fix is going into 13.4.0.
