### ISSUE TITLE
[BUG/ISSUE] Unexpected Crash on MAPL_CapGrim.F90 when run GCHP V13.0.0

### ISSUE THREAD

**Issue by chen-yuy** [geoschem/gchp#175]
Hello,
@LiamBindle @lizziel 
I am recently working on GCHP simulating, however, after one-year of successful simulation I met a crash when continuing my simulation as before and I have totally no idea why it happened.

The attaches are my files for running including the `runConfig.sh` and `HISTORY.rc`:
[HISTORY.rc.txt](https://github.com/geoschem/GCHP/files/7533187/HISTORY.rc.txt)
[runConfig.sh.txt](https://github.com/geoschem/GCHP/files/7533190/runConfig.sh.txt)

and my several error reports: 
[gchp.log.201901.txt](https://github.com/geoschem/GCHP/files/7533186/gchp.log.201901.txt)
[run_2530447.err.txt](https://github.com/geoschem/GCHP/files/7533188/run_2530447.err.txt)
[run_2530447.out.txt](https://github.com/geoschem/GCHP/files/7533189/run_2530447.out.txt)
[warnings_and_errors.log](https://github.com/geoschem/GCHP/files/7533191/warnings_and_errors.log)

I have noticed some similar `MAPL_Cap` related errors and discussions in github but none of them seem to be useful for my problem.
Looking forward to getting some useful info from you. 

Many thanks.

**Comment by LiamBindle** [comment]
Hi @chen-yuy, thanks for writing.

According to run_2530447.err.txt it failed on line 1391 or [MAPL/base/MAPL_CapGridComp.F90](https://github.com/geoschem/MAPL/blob/a9590432be58889e4277253c7872d982980e4bb3/base/MAPL_CapGridComp.F90#L1384-L1391):
```fortran
    call ESMF_TimeSet(   EndTime, YY = END_YY, &
         MM = END_MM, &
         DD = END_DD, &
         H = END_H , &
         M = END_M , &
         S = END_S , &
         calendar=cal,  rc = STATUS  )
    _VERIFY(STATUS)  
```

I'm not familiar with this section of code, but it looks like it's trying to create a time object called `EndTime`. Based on that I looked at your `runConfig.sh` and noticed the end time is Februrary 29th, 2019.

I believe Februrary in 2019 had 28 days. Could you try changing your end date to March 1, 2019?

---

Just so you know, logging was improved in 13.2. The poor error reporting here is because of a bug that meant errors in early-stages of set up weren't reported properly (just crashing quietly like it did here). When you have an opportunity to upgrade to a newer model version in the future, hopefully you'll find the logging is easier to understand.

**Comment by chen-yuy** [comment]
Hi @LiamBindle , thank you for your reply.

Exactly, the time setting issue caused this problem. I should have paid more attention to time settings.
Thank you so much!

I also came to another issue for the `HISTORY.rc` setting
After I commented several species I don't need in `Species_Conc` part of  `HISTORY.rc`, I could not run GCHP and got the following error. Do you have any idea about this problem, and could you please tell me how to comment out several species I don't need in a proper way?

Here is the errors file:
[gchp.log.201901_HISTORY.txt](https://github.com/geoschem/GCHP/files/7545131/gchp.log.201901_HISTORY.txt)
[run_2560127.err.txt](https://github.com/geoschem/GCHP/files/7545134/run_2560127.err.txt)

**Comment by LiamBindle** [comment]
@chen-yuy Great, happy to help.

Regarding your `HISTORY.rc` problem, it's likely a syntax error. You can find an overview of that file's format here: https://gchp.readthedocs.io/en/latest/supplement/config-files/HISTORY.html

Make sure you didn't accidentally comment out some of the attributes at the top of the SpeciesConc collection definition (e.g., `SpeciesConc.mode`, and also double check that you didn't remove the `::` at the end of the collection definition. If you don't see any syntax errors, could you share HISTORY.rc?

**Comment by chen-yuy** [comment]
@LiamBindle Thank you.
I am quite sure about my syntax. I just add the `#` before those species I don't need (as the attached HISTORY.rc file shows, I only comment out a few species such as `SpeciesConc_ACET` to do the test run), and get this error, while I remove all `#` it works.

By the way, I change the `SpeciesConc.mode` from `time-averaged to `instantaneous`.
Thank you for your help. :)
[HISTORY.rc.txt](https://github.com/geoschem/GCHP/files/7552504/HISTORY.rc.txt)

**Comment by LiamBindle** [comment]
The only thing that stands out in your HISTORY.rc file is that the `duration` and `frequency` of instantaneous collections is `40000` rather than `040000` (4-hourly). I haven't tested the MAPL input validation here, but the format is supposed to be HHMMSS.

The way you're commenting out variables is correct. If you confirm that that is in fact causing a crash, could you open a new issue for that? 

---

Side note. It's often a good idea to create custom collections according to what you need. The default collections include a lot of data, which most people won't need. In practice, it can save a lot of time down the road during analysis by using custom collection. For example, here's a collection for 4-hourly instantaneous values with 1-file per day (6 time slices per file). Hopefully it helps illustrate how you can create custom collections for your needs. See [here](https://gchp.readthedocs.io/en/latest/supplement/config-files/HISTORY.html) for more info.

```
DailyAvgGasesAndNOEmissions.template:     '%y4%m2%d2_%h2%n2z.nc4',
DailyAvgGasesAndNOEmissions.format:       'CFIO',
DailyAvgGasesAndNOEmissions.ref_date:     20170101
DailyAvgGasesAndNOEmissions.frequency:    040000
DailyAvgGasesAndNOEmissions.duration:     240000
DailyAvgGasesAndNOEmissions.mode:         'instantaneous'
DailyAvgGasesAndNOEmissions.fields:       'SpeciesConc_O3  ',  'GCHPchem',
                                          'SpeciesConc_NO  ',  'GCHPchem',
                                          'SpeciesConc_NO2 ',  'GCHPchem',
                                          'EmisNO_Total    ',  'GCHPchem',
                                          'EmisNO_Aircraft ',  'GCHPchem',
                                          'EmisNO_Anthro   ',  'GCHPchem',
                                          'EmisNO_BioBurn  ',  'GCHPchem',
                                          'EmisNO_Lightning',  'GCHPchem',
                                          'EmisNO_Ship     ',  'GCHPchem',
                                          'EmisNO_Soil     ',  'GCHPchem',
                                          'EmisNO2_Anthro  ',  'GCHPchem',
                                          'EmisNO2_Ship    ',  'GCHPchem',
                                          'EmisO3_Ship     ',  'GCHPchem',
                                          'Met_BXHEIGHT    ',  'GCHPchem',
                                          'Met_AIRDEN      ',  'GCHPchem',
                                          'Met_AD          ',  'GCHPchem',
::
```

**Comment by chen-yuy** [comment]
Thank you for your reply.
And yes, I will open a new issue for that.
