### ISSUE TITLE
[QUESTION] Mercury GCHP restart regridding

### ISSUE THREAD

**Issue by lfreese** [geoschem/gchp#200]
@arifein and I are working on getting Mercury GCHP simulations going, and are trying to create restart files from the GCClassic mercury restart. Is there a regridding routine that is available and being used to prep files? (We heard that @LiamBindle might have something along these lines)?

**Comment by LiamBindle** [comment]
Hi @lfreese, thanks for writing. You should be able to use [gcpy](https://github.com/geoschem/gcpy/tree/main/gcpy) for this. Here's an example of regridding [`GEOSCHEM_RESTARTS/v2018-11/initial_GEOSChem_rst.4x5_Hg.nc`](http://geoschemdata.wustl.edu/ExtData/GEOSCHEM_RESTARTS/v2018-11/initial_GEOSChem_rst.4x5_Hg.nc) to a C180 grid with the `python -m gcpy.file_regrid` command

```console
$ python -m gcpy.file_regrid -i initial_GEOSChem_rst.4x5_Hg.nc --dim_format_in classic -o initial_GEOSChem_rst.C180_Hg.nc --dim_format_out checkpoint --cs_res_out 180
```
The options are:
- `-i`: input file name
- `--dim_format_in `: the input file has dimension format of GC-Classic files
- `-o`: output file name
- `--dim_format_out`: the output file should use the dimension format of GCHP checkpoint (restart) files
- `--cs_res_out 180`: the output file should be C180

Note you can add `--sg_params_out S LON LAT` to generate a stretched-grid restart file.

If you have access to Docker or Singularity, you can run this command using the `geoschem/gcpy` container (so you can skip needing to install gcpy). Alternatively, if you can't use containers, you can install gcpy with [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html) using

```console
$ conda install gcpy -c conda-forge
```

or with pip using
```console
$ pip install git+https://github.com/geoschem/gcpy
```
but I haven't tried the pip install before.

Let me know if you have any issues.

**Comment by arifein** [comment]
Thanks @LiamBindle ! Just as a note, the conda command that worked for me is: `conda install geoschem-gcpy -c conda-forge`

**Comment by lizziel** [comment]
Yes, geoschem-gcpy is the correct package to install. We couldn't use the name gcpy since that already exists. You've probably already seen this, but just in case you haven't, here's the link to [GCPy's ReadTheDocs](https://gcpy.readthedocs.io/en/stable/index.html) which includes installation instructions. There is a section on regridding [here](https://gcpy.readthedocs.io/en/stable/Regridding.html).

**Comment by arifein** [comment]
Is there any way to create a 72-level restart from a 47-level GC-Classic restart? GCHP can only be run on 72 levels, correct? I am getting an error with GCHP: `File grid dimensions in GCHP_restart.nc4 do not match grid`

**Comment by lfreese** [comment]
Thanks all! @LiamBindle my gcpy doesn't have the file_regrid module (I've tried it both in the terminal and in a jupyter notebook). Is this from a certain version of gcpy? I re-downloaded it just now and still have the error that says 'file_regrid does not exist'

**Comment by LiamBindle** [comment]
Sorry @arifein, this fell through the cracks. I'm not aware of a good way to generate a checkpoint file from a 47-layer GC-Classic file. I suspect one would need to introduce a second restart/checkpoint file to introduce data for the layers above. GCHP can only run in the 72-layer configuration.

I'm going to close this issue but feel free to reopen if there's anything else.

**Comment by sdeastham** [comment]
One side comment - it's worth noting that the "additional" layers in the 72-layer version are all integer subdivisions of the layers in the 47-layer version (since both have the same model top at 1 Pa: http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_vertical_grids#47-layer_reduced_vertical_grid). The easiest thing to do would probably be:

1. "Vertically regrid" the 47-layer GC-Classic data to 72 layers (duplicating data in subdivided layers); then
2. Horizontally regrid the data to GCHP and save as a GCHP restart file.
