### ISSUE TITLE
[FEATURE REQUEST] Tagged ozone simulation in the future?

### ISSUE THREAD

**Issue by xpye98** [geoschem/gchp#201]
# Request a new GCHP feature

 

I wonder if there is a plan to include tagged ozone simulation in the future?
Is it hard due to the model structure?

**Comment by lizziel** [comment]
Hi @xpye98. I don't see any structural problems that would get in the way of a tagged ozone simulation in GCHP, but pinging @yantosca on that as he has been working on that simulation lately for GC-Classic.

Since tagged ozone is considered a specialty simulation we would look to the community for someone to put together a functional tagged ozone run directory for GCHP and test it for submission. Would you be interested in doing this work? We would be happy to advise on any questions that arose during that development.

**Comment by xpye98** [comment]
@lizziel Thanks for reply!
Yes, I'm willing to make a contribution to this function for the community. I'm not quite familiar with the structure, so it may take some time, but it'd be nice if I can help.

**Comment by lizziel** [comment]
That's really great! Definitely reach out with any questions you have.

**Comment by yantosca** [comment]
Thanks for writing @xpe98.  You might want to wait until 13.4.0 ships.  The tagged O3 simulation has been updated, see PR [#1150](https://github.com/geoschem/geos-chem/pull/1150) for details.  I think it would be pretty easy to set up a GCHP rundir for tagged O3 (but you might need to create a new restart file).

**Comment by xpye98** [comment]
see https://github.com/geoschem/geos-chem/pull/1167

**Comment by msulprizio** [comment]
The PR for this feature request (https://github.com/geoschem/geos-chem/pull/1380) has now been merged into `dev/14.1.0`.
