### ISSUE TITLE
forrtl: error (75): floating point exception: floating-point divide by zero

### ISSUE THREAD

**Issue by SadiaToma** [geoschem/gchp#211]
Hi,
Good afternoon. While running a GCHP simulation I am getting the error. interestingly, all my three scenario simulations are crashing at the same time with the same error. 

**forrtl: error (75): floating point exception**
Image              PC                Routine            Line        Source             
gchp               0000000002EE26BB  Unknown               Unknown  Unknown
libpthread-2.31.s  0000148DDC2FC3C0  Unknown               Unknown  Unknown
**gchp               00000000007BFC29  ratelawutilfuncs_         271  rateLawUtilFuncs.F90**
gchp               00000000007C56B2  fullchem_ratelawf        3095  fullchem_RateLawFuncs.F90
gchp               00000000007BB017  gckpp_rates_mp_up         715  gckpp_Rates.F90
gchp               00000000005115DC  fullchem_mod_mp_d         806  fullchem_mod.F90
gchp               00000000004C68DC  chemistry_mod_mp_         309  chemistry_mod.F90
gchp               0000000000492611  gchp_chunk_mod_mp        1328  gchp_chunk_mod.F90
gchp               0000000000472C7B  chem_gridcompmod_        3594  Chem_GridCompMod.F90
gchp               00000000004854F0  chem_gridcompmod_        2673  Chem_GridCompMod.F90
gchp               0000000002355CB4  Unknown               Unknown  Unknown

I have tried to trace back the error by looking at the file. It looks like the error is originating at line 271 while calculating the value of Khet. The denominator of the Khet becomes zero for a negative value of xx (xx = -1.0). Although according to the file xx should not have any negative value, but I am getting negative values for xx. 

`    !------------------------------------------------------------------------
    ! Grid-average loss frequency
    !
    ! EXACT expression for entrainment-limited uptake
    !------------------------------------------------------------------------

    ! Ratio (in cloud) of heterogeneous loss to detrainment, s/s
    kk = kI * tauc

    ! Ratio of volume inside to outside cloud
    ! ff has a range [0,+inf], so cap it at 1e30
    ff = SafeDiv( H%CldFr, H%ClearFr, 1.0e+40_dp )
    ff = MIN( ff, 1.0e+40_dp )

    ! Ratio of mass inside to outside cloud
    ! xx has range [0,+inf], but ff is capped at 1e30, so shouldn't overflow.
    xx =     ( ff        - kk        - 1.0_dp       ) / 2.0_dp +             &
         SQRT( 1.0_dp    + ff*ff     + kk*kk                   +             &
               2.0_dp*ff + 2.0_dp*kk - 2.0_dp*ff*kk ) / 2.0_dp

    ! Overall heterogeneous loss rate, grid average, 1/s
    ! kHet = kI * xx / ( 1d0 + xx )
    !  Since the expression ( xx / (1+xx) ) may behave badly when xx>>1,
    !  use the equivalent 1 / (1 + 1/x) with an upper bound on 1/x
    kHet = kI / ( 1.0_dp + SafeDiv( 1.0_dp, xx, 1.0e+40_dp ) )

    ! Overall loss rate in a particular reaction branch, 1/s
    kHet = kHet * branch`

I tried changing the cap of 'ff' from 1e30 to others, but it is not affecting the value of xx that much. I would appreciate it if anyone can help me with this issue. 

[slurm-53668.out (1).txt](https://github.com/geoschem/GCHP/files/8335186/slurm-53668.out.1.txt)
[rateLawUtilFuncs.F90.txt](https://github.com/geoschem/GCHP/files/8335197/rateLawUtilFuncs.F90.txt)

**Comment by yantosca** [comment]
Thanks for writing.  This code was recently updated (see https://github.com/geoschem/geos-chem/issues/906).

We could always flush xx to zero but we should understand where the negative values are originating from.  If it is the FF term then there is a problem in reading/regriddding data because those are cloud fractions.   If it is the kI term then that might mean a concentration is blowing up somewhere.

**Comment by SadiaToma** [comment]
Thanks, @yantosca for your reply. I printed out the values of ff and kk, but could not get a clue of what's triggering the negative xx. Moreover, it looks like '1.0_dp' should be replaced by '1.0_fp' in the formula of xx. The older version of the GCHP, that I am using, does not have 'fp' defined within the script and the function of "ClouldHet' is also slightly different. Given my limited knowledge of GCHP source code, could you please explain what is the difference between dp vs fp ? That would also help me to figure out whether ff or kk is causing the negative value xx. Thanks for your support.

Sadia

**Comment by yantosca** [comment]
Thanks @SadiaToma.  In GEOS-Chem the _dp specifies REAL\*8 precision within the KPP code.  The _fp specifies flexible precision, it can be toggled to REAL\*4 or REAL\*8 but to ensure numerical stability it is set to REAL\*8 by default.

**Comment by SadiaToma** [comment]
Thanks, @yantosca for your prompt response. I did print some of the negative xx values and their corresponding ff and kk values, but not getting any clues which one is triggering the negative values of xx. Do you have any idea about what's causing that negative value? 

![Neg_xx](https://user-images.githubusercontent.com/50336503/159970292-8b4bb2f6-03d6-4e37-89c7-07afc4a9dd9a.PNG)

However, flushing the xx to zero solves the issue. It is worth mentioning here that the version of KPP we are using defines everything as '_dp', not as '_fp'.

**Comment by sdeastham** [comment]
I think this is really a problem in GC, not GCHP. The function appears to be unstable for values of `kk` around 1e16. Check this out:

![image](https://user-images.githubusercontent.com/6618732/160702730-b14dd3d0-1355-46d6-838d-ac486a7f68de.png)

A short-term fix is just to force `xx` to zero if it becomes negative. But it would be good to understand under what circumstances `kk` reaches 1e16 (i.e. is this a plausible situation or is something wrong upstream?). If it's actually expected that `kk` reaches 1e16 then there could be an algorithmic issue here - I think the problem is related to precision. Try out the code below to reproduce:

```
import numpy as np
import matplotlib.pyplot as plt

def xx_double(ff,kk):
    fd = np.double(ff)
    kd = np.double(kk)
    d1 = np.double(1.0)
    d2 = np.double(2.0)
    xx = (fd - kd - d1) / d2 + np.sqrt( d1 + fd * fd + kd * kd + 
                                        d2 * fd + d2 * kd - 
                                        d2 * fd * kd) / d2
    return xx

def xx_quad(ff,kk):
    fq = np.longdouble(ff)
    kq = np.longdouble(kk)
    q1 = np.longdouble(1.0)
    q2 = np.longdouble(2.0)
    xx = (fq - kq - q1) / q2 + np.sqrt( q1 + fq * fq + kq * kq + 
                                        q2 * fq + q2 * kq - 
                                        q2 * fq * kq) / q2
    return xx

ff = np.double(0.198522515156093)
kk = np.double(1.093239167698677e+16)
kk_range = np.linspace(0.99,1.01,1001) * kk

f, ax = plt.subplots(1,1)
ax.plot(kk_range,xx_double(ff,kk_range),'-b',label='double precision')
ax.plot(kk_range,xx_quad(ff,kk_range),'-r',label='quad precision')
ax.legend()
```

**Comment by lizziel** [comment]
This issue is fixed by https://github.com/geoschem/geos-chem/pull/1206 that was included in 13.4.0.

**Comment by sdeastham** [comment]
@lizziel while this fix does indeed prevent simulation failure, I realized that flushing to zero is only a partial fix. For very high reaction rates (`kI`), `xx` (the in-cloud to out-of-cloud ratio of mass) absolutely should be zero - all mass in the cloud should be reacted away. The problem was that `xx` was ending up being set arbitrarily to -1 and +1 (see earlier post). -1 is nonsense, so the simulation crashed. But +1 is a problem too - it means that the heterogeneous chemistry rate `kHet` will end up being `kI / 2` rather than just `kI`, so the rate is actually halved incorrectly (!). I suspect this will be rare, but don't actually know for sure (and suspect also that this will get more common at higher resolutions). I think the safest thing to do would be to branch based on `kk` - so that `xx` is just set to zero if `kk` is sufficiently large. Happy to raise an issue if necessary.

**Comment by lizziel** [comment]
Yes, please raise this issue on the geos-chem issues page. Thanks!
