### ISSUE TITLE
[QUESTION] Does the vertical emissions distribution feature work in GCHP?

### ISSUE THREAD

**Issue by LukeFakes** [geoschem/gchp#212]
The [vertical emissions distribution](https://github.com/geoschem/HEMCO/issues/46) feature implemented in GCClassic v13.1 was really useful for my work. 

It looks as though the standard GCHP HEMCO_Config.rc doesn't use `xyL*` anywhere. Could I confirm that this isn't a GCHP feature at the moment?

**Comment by lizziel** [comment]
Hi @LukeFakes, this feature should work with GCHP as well. We use it for biomass burning emissions (see [here](https://github.com/geoschem/geos-chem/blob/9ab6931db5b556eafd0e002e9fd4fdbcbd5fbb44/run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem#L2603) as an example), though that option is turned off by default. If you try it and it doesn't work definitely let us know. There is currently an issue with GFAS in GCHP (see https://github.com/geoschem/GCHP/issues/183), but that will be fixed in 14.0.

**Comment by LukeFakes** [comment]
Hi @lizziel, you were right. They work in the same way as GCClassic. Thanks for confirming.
