### ISSUE TITLE
[QUESTION] Question about nested and output

### ISSUE THREAD

**Issue by Alex-Fang66** [geoschem/gchp#216]
# Ask a question about GCHP:

 

Hi, I am new to GCHP, and there are some questions confused me.
1、In GEOS-Chem classic, when we want a higher resolution like 05x0625, we should firstly run a 2x25 and take it as boundary for nested. It seems GCHP does not need run a lower resolution when run like c180?
2、In HISTORY.rc, it's fabulous to convert the output into lonlat directly, but we can choose higher resolution lonlat compared what we run without raise any error message. Is this because some interpolation is carried out directly, and is the output reliable?
3、We have to run with a global scale and 72 levels, right?
Best regard!

**Comment by yantosca** [comment]
Thanks for writing @Alex-Fang66 :

>1、In GEOS-Chem classic, when we want a higher resolution like 05x0625, we should firstly run a 2x25 and take it as boundary for nested. It seems GCHP does not need run a lower resolution when run like c180?

That is correct.  We recommend to run GCHP with the highest resolution meteorology possible (that you have disk space for) and it will regrid it on-the-fly to the currently selected resolution. 

>2、In HISTORY.rc, it's fabulous to convert the output into lonlat directly, but we can choose higher resolution lonlat compared what we run without raise any error message. Is this because some interpolation is carried out directly, and is the output reliable?

Am tagging @sdeastham, @LiamBindle, and @lizziel here, who might know more about this.

>3、We have to run with a global scale and 72 levels, right?

Correct.  But you can stretch the grid so that you can have a higher resolution over your area of interest.  See our stretched-grid tutorial here: https://gchp.readthedocs.io/en/latest/stretched-grid.html

**Comment by Alex-Fang66** [comment]
Thanks for the quick and kind reply. @yantosca
