### ISSUE TITLE
[BUG/ISSUE] Fix needed to get GCHP build matrix to pass

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gchp#223]
GCHP builds in the Azure pipelines have been failing since [updating to the latest GMAO libraries](https://github.com/geoschem/GCHP/pull/214) (git tag 14.0.0-alpha.2). See https://dev.azure.com/geoschem/GCHP/_build?definitionId=23. 

@LiamBindle wrote:

>I just took a glance at the Azure pipeline status. The problem is there's an undefined reference to a symbol in glibc. Initially I thought that pointed to something weird/compiler related behind the scenes (like a OS update) but that doesn't make sense since it runs in a container. I looked at the pipeline itself and noticed this started with the GMAO library upgrade, so it's likely a change in ESMA_cmake is what's broken it.
>
>I think the final link command is missing an -ldl at the end. Adding an
>
>`target_link_libraries(gchp PUBLIC -ldl)`
>
>would probably fix it.

We should probably try to fix this before the official 14.0.0 release so that the build matrix token on the GCHP repo main page does not say "failed."

**Comment by lizziel** [comment]
@LiamBindle, I assigned this to you for the coming weeks. If we decide to keep the tests this is a good opportunity to hand the maintenance of it off to someone else, perhaps at WashU?

**Comment by lizziel** [comment]
@LiamBindle, will you have time to tackle this during the summer?

**Comment by lizziel** [comment]
We have decided to retire the Azure pipelines for GCHP. Automatic builds are now done on AWS via github actions. All Azure pipeline code needs to be removed from the GCHP repository, and the README needs to be updated to exclude the build test results.

**Comment by lizziel** [comment]
I'd like to get this into 14.0.0 before the release. @LiamBindle, can you confirm that the only tasks are as follows:

1. Delete Azure pipeline badge from the `README`
2. Remove `MinimumStandaloneTransportTracer` submodule (I am aware the directory cannot simply be deleted)
3. Delete [.ci-pipelines](https://github.com/geoschem/GCHP/tree/dev/.ci-pipelines) directory in its entirety

I also plan to archive the `MinimumStandaloneTransportTracers` repository on GitHub since it is very outdated and no longer used.

Let me know if I am missing anything, or if there are any contents in `.ci-pipelines` that should not be deleted.

Thanks!

**Comment by lizziel** [comment]
Done!
