### ISSUE TITLE
[BUG/ISSUE] GCHP 14.1.0 compilation error

### ISSUE THREAD

**Issue by ShreyaSharmaMIT** [geoschem/gchp#286]
### What institution are you from?
Massachusetts Institute of Technology

### Description of the problem
There is an error when I try to cmake the code directory. The screenshot is attached.
<img width="1248" alt="Screenshot 2023-02-10 at 5 37 45 PM" src="https://user-images.githubusercontent.com/115248416/218214205-21bf6a71-85d1-4382-8ed7-6b83755646c0.png">

The cmake and make log files are attached:
[log.cmake.txt](https://github.com/geoschem/GCHP/files/10711959/log.cmake.txt)
[make log.txt](https://github.com/geoschem/GCHP/files/10711960/make.log.txt)

### GEOS-Chem version
14.1.0

### Software versions
- Compilers (Intel or GNU, and version): Intel 20.2.3.20210609
- NetCDF version: 4.7.3
- MPI version: 3.1
- ESMF version: 8.0.0

**Comment by lizziel** [comment]
Hi Shreya,

The error you are seeing is because it is trying to build ExtData2G which is the next generation of ExtData (input component of GCHP). It should be off by default, set in `CAP.rc` as `USE_EXTDATA2G: .FALSE.`. This should already be set for you if you created a run directory from the 14.1.0 source code. Did you do that?

I see that you are using ESMF 8.0.0. You may run into problems with this since I think the latest MAPL in the model requires 8.1+. ReadTheDocs unfortunately has not been updated to reflect that.

NOTE: We are now asking users to identify themselves and their institutions when requesting help. Please do this in the future. Thanks!

**Comment by lizziel** [comment]
Hi @ShreyaSharmaMIT, were you able to resolve this issue?

**Comment by Twize** [comment]
@ShreyaSharmaMIT I encountered a similar issue when compiling GCHP v14.1.0 with ESMF v8.0.1. Using a newer version of ESMF (e.g. v8.3.0) enabled me to get past this.

**Comment by yantosca** [comment]
@ShreyaSharmaMIT @Twize: Yes, the newer MAPL library in GCHP 14.1.0+ requires at least ESMF 8.1.0+.  We ran into this as one day all of our GCHP integration tests and cloud benchmarks were failing.  You can use ESMF 8.3.0 or 8.4.0 and that should be OK.

**Comment by lizziel** [comment]
ReadTheDocs is updated in 14.1.1 to reflect that GCHP now requires ESMF 8.1+.
