### ISSUE TITLE
[QUESTION] installing intel-oneapi-compilers fails

### ISSUE THREAD

**Issue by hmhorow** [geoschem/gchp#290]
# installing compiler issue:
Hannah Horowitz from UIUC here. 
I am following the readthedocs instructions here: https://gchp.readthedocs.io/en/latest/supplement/building-gchp-dependencies.html#install-the-recommended-compiler
The first step fails (I am doing this from the directory in which I have cloned GCHP; GCHP/spack exists). I have no idea how to proceed. I've used spack to install lots of software before. 

```
(base) [hmhorow@golubh4 GEOSChem]$ spack -C GCHP/spack install intel-oneapi-compilers
==> Installing patchelf-0.10-6k6b65iomk4n6s3542zlbw5lq57qraoc
==> Warning: Skipping build of intel-oneapi-compilers-2021.1.0-dkeqmzodxjg3ogwsg5ut3ldyeatm52b6 since patchelf-0.10-6k6b65iomk4n6s3542zlbw5lq57qraoc failed
==> Error: Failed to install patchelf due to AttributeError: 'NoneType' object has no attribute 'replace'
```

I have no idea if this is because our campus cluster has cmake version 3.18.4. I don't think I will be able to get them to upgrade to 3.19 or above (e.g. #85  ). Is that the only way? I am not sure I can install cmake myself because everything I find online requires the use of 'sudo' and I am not going to be able to do that on our campus server. 

Thanks for your help!

**Comment by yantosca** [comment]
Hi @hmhorow.  I am going to tag @Jourdan-He, @lizziel, and @1Dandan who may have seen this issue before.

The other thing you can do is to see if your cluster already has the proper library builds.  For example on the Harvard Cannon cluster we use these versions:
```console
  1) git/2.17.0      7) zlib/1.2.11
  2) gmp/6.2.1       8) szip/2.1.1
  3) mpfr/4.1.0      9) hdf5/1.10.7
  4) mpc/1.2.1      10) netcdf/4.8.0
  5) gcc/10.2.0     11) netcdf-fortran/4.5.3
  6) openmpi/4.1.0  12) cmake/3.16.1
```
Some of the libraries (like gmp, mpfr, etc) are dependencies of e.g. gcc or openmpi.

**Comment by 1Dandan** [comment]
I did not try to install compiler itself as they are already installed on the cluster. I am also wondering whether there is available intel compiler on your @hmhorow cluster already? For the error of failing `patchelf`, maybe trying to install the original interlOneapi directly following the instruction of https://spack.readthedocs.io/en/latest/build_systems/inteloneapipackage.html#compilers to see if the error persist?

**Comment by lizziel** [comment]
I am tagging @mathomp4 (GMAO) who has had experience with Intel oneAPI not playing well with CMake, although it looks like the error message is python not CMake.  Also curious is the [IntelOneapi docs](https://spack.readthedocs.io/en/latest/build_systems/inteloneapipackage.html) uses package `patchelf` in the examples of how to install using the Intel compilers _after IntelOneapi is already installed_.

**Comment by mathomp4** [comment]
@lizziel It's been a while since I've tried spack + Intel oneAPI. At home when I test, I stick with GCC because, well, it works better. 

Any success I've had has been thanks to either work by @climbfuji (who has maybe seen this error) or by NCCS folks. I'll reach out to the NCCS person (though I think he's on vacation)...

That said, the spack work I've done with NCCS folks on AWS has been with spack installed oneAPI so it must be doable!

One note: Intel being intel, you'll want to make sure you "build" Intel with a new enough GCC. Intel C and C++ uses gcc/g++ behind the scenes. So often you have to install, say, GCC 10 or 11 and then install oneAPI with that compiler. Only so the spack installed oneAPI sees that `gcc` resolves GCC 10 or 11 and not maybe an ancient OS supplied version.

**Comment by climbfuji** [comment]
I don't think you want to *build* Intel oneAPI with spack, but rather use the available packages. See https://github.com/NOAA-EMC/spack-stack/tree/develop/configs/sites/discover for the example of Discover. It also has the newer C++ backend that @mathomp4 described.

**Comment by lizziel** [comment]
Hi @hmhorow, were you able to get GCHP working using Spack-built libraries?

**Comment by yantosca** [comment]
Hi @hmhorow @lizziel: We have now rewritten the Spack installation instructions so that we use gcc instead of intel-oneapi-compilers.  Please try the new instructions at https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/spack-guide.html and let us know if you encounter any issues.  I'll also open up a new issue on geoschem/geos-chem as a discussion topic for people to post updates.

The new instructionis will build esmf 8.1.0, gcc 10.2.0, openmpi 4.1.0, as these versions have been proven to work together on the Harvard Cannon cluster.  I built these successfully with the new instructions on my PC (Ubuntu 22.04 running under Windows Subsysterm for Linux) and on a bare-bones AWS cloud AMI.
