### ISSUE TITLE
Issues running GCHPctm with GEOS-Chem 12.8.2

### ISSUE THREAD

**Issue by aechristiansen** [geoschem/GCHP#31]
Hi, I'm trying to get the GCHPctm wrapper working in the default standard simulation with MERRA2, using GEOS-Chem 12.8.2. I was able to build the geos executable following the "getting started" portion of the GCHPctm GitHub page, I am running into some problems with running the default (6-core, 1-node, 1-hour) test simulation. I am running interactively using the gchp.local.run script available in the runScriptSamples directory.

More information:
-I am running on the NCAR Cheyenne system, which uses a PBS scheduling system
-My interactive session uses 1 node with 36 cores/node
-I am using openmpi 4.0.3 and gfortran 8.3.0 compiler
-I built ESMF with ESMF_COMM=openmpi

I receive this output when running the default:

```
WARNING: NX and NY are set such that NX x NY/6 has side ratio >= 2.5. Consider adjusting resources in runConfig.sh to be more square. This will avoid negative effects due to excessive communication between cores.
Compute resources:
NX                             : 1                    GCHP.rc             
NY                             : 30                   GCHP.rc             
CoresPerNode                   : 30                   HISTORY.rc          
 
Cubed-sphere resolution:
GCHP.IM_WORLD                  : 24                   GCHP.rc             
GCHP.IM                        : 24                   GCHP.rc             
GCHP.JM                        : 144                  GCHP.rc             
IM                             : 24                   GCHP.rc             
JM                             : 144                  GCHP.rc             
npx                            : 24                   fvcore_layout.rc    
npy                            : 24                   fvcore_layout.rc    
GCHP.GRIDNAME                  : PE24x144-CF          GCHP.rc             
 
Initial reestart file:
GIGCchem_INTERNAL_RESTART_FILE : +initial_GEOSChem_rst.c24_standard.nc GCHP.rc             
 
Simulation start, end, duration:
BEG_DATE                       : 20160701 000000      CAP.rc              
END_DATE                       : 20160701 010000      CAP.rc              
JOB_SGMT                       : 00000000 010000      CAP.rc              
 
Checkpoint (restart) frequency:
RECORD_FREQUENCY               : 100000000            GCHP.rc             
RECORD_REF_DATE                : 20160701             GCHP.rc             
RECORD_REF_TIME                : 000000               GCHP.rc             

```

The run eventually crashes after reading the HEMCO_Config.rc file and gives this error: 

```
FATAL from PE     1: mpp_domains_define.inc: not all the pe_end are in the pelist
FATAL from PE     3: mpp_domains_define.inc: not all the pe_end are in the pelist
FATAL from PE     5: mpp_domains_define.inc: not all the pe_end are in the pelist
FATAL from PE     0: mpp_domains_define.inc: not all the pe_end are in the pelist
FATAL from PE     2: mpp_domains_define.inc: not all the pe_end are in the pelist
FATAL from PE     4: mpp_domains_define.inc: not all the pe_end are in the pelist
FATAL from PE     0: mpp_domains_define.inc: not all the pe_end are in the pelist
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[r1i2n17:64901] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2193
[r1i2n17:64901] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2193
[r1i2n17:64901] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2193
[r1i2n17:64901] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2193
[r1i2n17:64901] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2193
[r1i2n17:64901] 5 more processes have sent help message help-mpi-api.txt / mpi-abort
[r1i2n17:64901] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

I am quite new to this, so I am not sure what is going on and would appreciate any advice. Further, are there potential issues I might run into by attempting to use GEOS-Chem 12.8.2 with GCHPctm? I am happy to provide more info if needed, as well. The full output log is attached.
[gchp.pdf](https://github.com/geoschem/GCHPctm/files/4887044/gchp.pdf)

**Comment by lizziel** [comment]
Hi @aechristiansen , I believe this is a bug in our run directory files. The runConfig.sh template file used when creating the run directory now has 30 cores per node by default, which is what is used in the sample run script gchp.run. I think gchp.local.run was not updated to use 30 cores and instead still specifies 6.

For future reference, I was able to figure this out by looking at the the resources listed in your log file. At the very top there is a dump of the settings set by configuration in runConfig.sh. For your run you have this, indicating 30 cores are expected:
```
Compute resources:
NX : 1 GCHP.rc
NY : 30 GCHP.rc
CoresPerNode : 30 HISTORY.rc 
```
However, in gchp.local.run (assuming you are using the default that comes with GEOS-Chem) nCores is still set to 6. This is used in the run command that tells your machine how many cores to use. It also shows up in the log file, just before your run crashed:
```
 Starting PEs : 6
 Starting Threads : 36
FATAL from PE 1: mpp_domains_define.inc: not all the pe_end are in the pelist
```
The message about PEs is an indicator there's an issue with number of cores, in this case a mismatch between what GCHP expects and what is available. PE stands for persistent execution, and is usually seen in the context of PETs which is persistent execution threads. # PETs = # cores.

Try doing either of the following: (1) change NY and CoresPerNode to 6 in runConfig.sh to use 6 cores, or (2) update your run script to set nCores to 30 to use 30 cores. Let us know if that fixes it. We can put the fix for gchp.local.run into the next version of GEOS-Chem.

**Comment by aechristiansen** [comment]
Thank you very much for your help and the detailed explanation. I tested out both independently, and they both fix the problem.

**Comment by lizziel** [comment]
I'm glad it worked. I kept the default in gchp.local.run to 6 and updated the comment in the file to specify that runConfig.sh should be changed to match the value of nCores. I also updated the wiki entry on using gchp.local.run to be more clear that the resources in the run script and runConfig.sh must match, along with the specific variables to look at.

Thanks for raising this issue!
