### ISSUE TITLE
Questions: Coordinates used for GCHP restart files

### ISSUE THREAD

**Issue by 1Dandan** [geoschem/gchp#319]
### Name and Institution (Required)

Name: Dandan Zhang
Institution: Washington University in St. Louis

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [x] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question
Hi,
    I am trying to plot the GCHP restart files but confused about the coordinates used for restart files. The variables of `lat` and `lon` seem just indices without actual values. Are the coordinates for GCHP restart files the same as diagnostics at corresponding resolution? Is it concatenated by the same order of face index in the diagnostics? 
    GCPy seems having the functionality of regridding between checkpoints and diagnostics before, but I could not find it on the latest [GCPy doc](https://gcpy.readthedocs.io/en/stable/Regridding.html) now.
    Could you help me with it?

**Comment by 1Dandan** [comment]
To update, sorry that I realized file_regrid function in gcpy is still valid, but still got several questions to confirm with you.
1) `checkpoint` is vertically flipped with surface level at 72 layer, and 'diagnostic` is normal with first layer being the surface layer, right? 
2) Also, regridding from `checkpoint` to `diagnostic` at same resolution will not result in any flipping of vertical dimension, right? So the regridded file from `checkpoint` to `diagnostic` will still be vertically flipped?

**Comment by lizziel** [comment]
Hi @1Dandan, unfortunately the restarts and diagnostic (History) files in GCHP use different formats. Way long ago the diagnostic files used the same format as the restarts but since then have been updated to use a better format, i.e. ones that contain coordinates. The restarts are still the old version but GMAO hopes to change that at some point in the future. For now we stuck with the old format.

Here is some info on the two formats. I'll plan to put this on ReadTheDocs in the future. I'll put another comment addressing your questions/comments on GCPy.

**Restart file:**
```
dimensions:
        lon = 24 ;
        lat = 144 ;
        lev = 72 ;
        time = 1 ;
variables:
        double lat(lat) ;
                lat:standard_name = "latitude" ;
                lat:long_name = "Latitude" ;
                lat:units = "degrees_north" ;
                lat:axis = "Y" ;
        double lev(lev) ;
                lev:standard_name = "level" ;
                lev:long_name = "Level" ;
                lev:units = "level" ;
                lev:axis = "Z" ;
        double lon(lon) ;
                lon:standard_name = "longitude" ;
                lon:long_name = "Longitude" ;
                lon:units = "degrees_east" ;
                lon:axis = "X" ;
        double time(time) ;
                time:standard_name = "time" ;
                time:long_name = "Time" ;
                time:units = "minutes since 2019-07-01 00:00:00" ;
```

As you point out, these dimensions are simply indexes and are not coordinates. For example:
` lon = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24 ;`

This is not a problem when GCHP reads and writes the restart files because MAPL can compute the coordinate mapping given any grid resolution, e.g. c48. In GCPy we compute the coordinates that correspond to the lat and lon index values using a standard cubed-sphere grid formula and then adjust it to correspond to GMAO's specific cubed sphere face orientation. See functions [csgrid_GMAO](https://github.com/geoschem/gcpy/blob/84d11cb1769e1fff938d1256cb2b90d84b75edfd/gcpy/grid.py#L988) and [CSGrid](https://github.com/geoschem/gcpy/blob/84d11cb1769e1fff938d1256cb2b90d84b75edfd/gcpy/grid.py#L1026) in `gcpy/gcpy/grid.py`. This code was developed by former Harvard grad student Jiawei Zhuang. Notice that the lon dimensions is 6 x 24 = 144, while the lat dimension is 24. If you count all unique combinations of lat index and lon index you get 6x24x24, which covers all horizontal grid cells at c24.

**Diagnostic file:**
```
dimensions:
        XCdim = 25 ;
        Xdim = 24 ;
        YCdim = 25 ;
        Ydim = 24 ;
        lev = 72 ;
        ncontact = 4 ;
        nf = 6 ;
        orientationStrLen = 5 ;
        time = UNLIMITED ; // (1 currently)
variables:
        double Xdim(Xdim) ;
                Xdim:long_name = "Fake Longitude for GrADS Compatibility" ;
                Xdim:units = "degrees_east" ;
        double Ydim(Ydim) ;
                Ydim:long_name = "Fake Latitude for GrADS Compatibility" ;
                Ydim:units = "degrees_north" ;
        int nf(nf) ;
                nf:axis = "e" ;
                nf:grads_dim = "e" ;
                nf:long_name = "cubed-sphere face" ;
        int ncontact(ncontact) ;
                ncontact:long_name = "number of contact points" ;
        int contacts(nf, ncontact) ;
                contacts:long_name = "adjacent face starting from left side going clockwise" ;
        int anchor(nf, ncontact, ncontact) ;
                anchor:long_name = "anchor point" ;
        double lons(nf, Ydim, Xdim) ;
                lons:long_name = "longitude" ;
                lons:units = "degrees_east" ;
        double lats(nf, Ydim, Xdim) ;
                lats:long_name = "latitude" ;
                lats:units = "degrees_north" ;
        double corner_lons(nf, YCdim, XCdim) ;
                corner_lons:long_name = "longitude" ;
                corner_lons:units = "degrees_east" ;
        double corner_lats(nf, YCdim, XCdim) ;
                corner_lats:long_name = "latitude" ;
                corner_lats:units = "degrees_north" ;
        double lev(lev) ;
                lev:coordinate = "eta" ;
                lev:long_name = "vertical level" ;
                lev:positive = "down" ;
                lev:standard_name = "model_layers" ;
                lev:units = "layer" ;
        float time(time) ;
                time:begin_date = 20190101 ;
                time:begin_time = 10000 ;
                time:long_name = "time" ;
```

The diagnostic files actually contain the coordinates, in variables lats and lons, and they are used in a standard format that  some viewers, such as Panoply, can readily handle. The example shows the dimensions of each are 6x24x24 which covers all horizontal cells in a c24 global cubed sphere grid.

**Comment by 1Dandan** [comment]
Thanks @lizziel for your detailed reply! The information you shared is very helpful. For actual processing, I simple leverage on the tools available in GCPy, specifically file_regrid.py to regrid `checkpoint` and `diagnostics` and then extract coordinates from one of the diagnostics from model outputs at same resolution with vertical dimension flipped with first layer to be surface layer. I am not familiar with restarts file construction, so I am wondering whether this makes sense to you or not.

### Detailed information about the scripts I used
To obtain restart file in "normal" dimension as diagnostic:
```
import xarray as xr
from gcpy.file_regrid import file_regrid

InDir = '/ExtData/GEOSCHEM_RESTARTS/GC_13.0.0/'
OutDir = '/my-projects2/AnalData/Restarts/'
gridDir = '/my-projects/supportData/gridinfo/'

cres = 'C48'
numcres = 48

fin = InDir + 'GCHP.Restart.fullchem.20190101_0000z.{}.nc4'.format(cres.lower())
fout = OutDir + 'Reformat.GCHP.Restart.fullchem.20190101_0000z.{}.nc4'.format(cres.lower())

file_regrid(
    fin,
    fout,
    dim_format_in='checkpoint',
    dim_format_out='diagnostic',
    cs_res_out=numcres,
)
```

And then I assume the coordinates of the regridded file (`Reformat.GCHP.Restart.fullchem.20190101_0000z.c48.nc4`) are in the same dimension as any of diagnostics at C48, so I simply extracts variables `lats`, `lons`, `corner_lats`, and `corner_lons` to be appended to the file and then do plotting.

The full scripts I used are:
[Reformat_restart_file.py.txt](https://github.com/geoschem/GCHP/files/11638689/Reformat_restart_file.py.txt)

**Comment by lizziel** [comment]
> 1. checkpoint is vertically flipped with surface level at 72 layer, and 'diagnostic` is normal with first layer being the surface layer, right?

Correct. All restart (checkpoint) files have level 1 correspond to top-of-atmosphere and level 72 at surface. Diagnostic (history) files are the opposite, with the exception of the Emissions collection. That collection is still vertically flipped, although that will change in v15 so that all diagnostic files are consistent.


> 2. Also, regridding from checkpoint to diagnostic at same resolution will not result in any flipping of vertical dimension, right? So the regridded file from checkpoint to diagnostic will still be vertically flipped?

I think the functionality in GCPy you are referring to is function [file_regrid](https://github.com/geoschem/gcpy/blob/84d11cb1769e1fff938d1256cb2b90d84b75edfd/gcpy/file_regrid.py#L21). My understanding is that that function is not regularly used for GCHP files and may or may not work. It was developed by @LiamBindle and needs attention from GCST but we have not had a chance to get to it. Would you be able to test it out? If not, I can try to get to this next week. We now point people to a new function in GCHP to regrid restart files, but that is only from one grid resolution to another and does not include reformatting into the diagnostic file format.

**Comment by 1Dandan** [comment]
Hi @lizziel, thanks for your reply. 
I also learned that regridding restarts by file_regrid is not recommended. I used file_regrid to generate restarts for stretching simulations which would prompt errors. Using the new `regrid_restart_file` works well for generating restarts for stretching simulations. 
Using `file_regrid` to regrid non-stretch restarts seem still working, but I only tried to regrid between cubed-sphere restarts at different resolutions. 
For the current functionality I used with `file_regrid` to regrid between `checkpoint` and `diagnostic`, it did not show any error. The results seem ok to me.
The regridded file generated by "file_regrid" with coordinate variables added from C48 diagnostics:
https://wustl.box.com/s/51flm2w9509sqc9qlvjxqzlgojyiuxcf

Would you have any suggestions for other tests?

**Comment by lizziel** [comment]
Hi @1Dandan, thanks for reporting `file_regrid` is still working to regrid non-stretch GCHP restarts between cubed-sphere resolutions. @kilicomu has been working on regridding so I am looping him in here.

We are in the process of overhauling the regridding in GEOS-Chem to make it more intuitive and make sure everything works. As part of that I think we should move the transformation between GCHP checkpoint file format and history file format out of `file_regrid` since it is not a true regrid. It makes sense to be able to specify what kind of output format you want when regridding, but I don't think it makes sense to have to use `file_regrid` if you want to just change the format of a file. It is also confusing that we now have `file_regrid` as well as `regrid_restart_file`. We need to figure out what the GCPy regrid functionality will be and come up with a more intuitive set of functions to choose from. We hope to further develop and test the regridding capabilities of GCPy by the end of the year but it is not a big priority right now for GCST since our GCPy focus is primarily benchmarking.

The best way to test if file regrid is working is to inspect the results as you are already doing. If you are only reshaping the file, e.g. going between checkpoint and diagnostic file format without regrid, then you can open both files in python and do data analytics to make sure the values are identical. You could also change a restart file to diagnostic format, and then back to checkpoint format, and diff the original and final files to make sure nothing changed and that you can still use it as a restart file in GCHP.

**Comment by 1Dandan** [comment]
Thanks @lizziel for sharing relevant information and suggestions for checking regridding results.
