### ISSUE TITLE
How to input customized Cubed Sphere Emissions input in GCHP ?

### ISSUE THREAD

**Issue by deepangsu** [geoschem/gchp#325]
I have a question:

My current understanding of emissions input process in GCHP is through HEMCO_Config.rc and ExtData.rc 

I have gone through these files and found that the input emissions files are always in Lat Lon grid along with spatially distributed scale factors/total scale factors. MAPL regrids the Lat Lon emissions to Cubed sphere emissions for GCHP.

Could you please explain, for a case where I have customized emissions which are essentially cube sphere, how can I input them through HEMCO_Config.rc or ExtData.rc ?

I understand I can do a offline regirding of the emissions to convert them to Lat Lon and have them as input. But I was wondering if there is a way to input cubed sphere emissions to gchp ?

**Comment by lizziel** [comment]
Hi @deepangsu, you can include cubed-sphere resolution file in `ExtData.rc` the same way you would lat-lon files, by simply listing the filename. MAPL will regrid them as needed to the target cubed-sphere resolution.

That being said, you describe your files as "essentially cube sphere." What does that mean? The files must be on a standard cubed sphere grid in the same format you would see the GCHP output diagnostic files, just potentially at a different grid resolution.

**Comment by lizziel** [comment]
See also this directory for examples of cubed sphere files that GCHP can input: http://geoschemdata.wustl.edu/ExtData/GEOS_C720/GEOS_FP_Native/Y2022/M04/D04/

These are C720 files containing a few variables, such as mass fluxes, that may be used in advection in place of lat-lon fields. You can try using these inputs by creating a GCHP run directory and specifying GEOS-FP native fields as meteorology, and then choose mass fluxes.

**Comment by deepangsu** [comment]
Hi @lizziel , thank you for your response. 

What I meant my by "essentially cube sphere" is what would happen with the Lat-Lon gridded scale factors. We should also regrid all Lat-Lon gridded scaling factors to cubed-sphere. Or will MAPL be able to handle cubed sphere emissions and Lat-Lon scale factors as input ?

**Comment by lizziel** [comment]
Hi @deepangsu, MAPL can handle either gridded lat-lon or cubed sphere inputs, whether they be gridded meteorology, gridded emissions, or gridded scale factors. Now, whether the regridding of the scale factors and emissions makes sense physically is another question. Is that what you are asking?

**Comment by deepangsu** [comment]
Hi @lizziel, can you share ExtData.rc and HEMCO_Config.rc files for a simulation that input cubed sphere emissions to GCHP 14.1.1 . It would be easier for me to understand the file formatting, since the default ExtData.rc and HEMCO_Congfig.rc files are set up with default LAT-LON emissions.

**Comment by lizziel** [comment]
Hi @deepangsu,
Yes, see [here](https://github.com/geoschem/geos-chem/blob/main/run/shared/settings/native_geosfp_mass_flux.txt) for the `ExtData.rc` format of input cubed-sphere meteorology files. You can create the full `ExtData.rc` file that uses it by creating a GCHP run directory and choosing "GEOS-FP native" meteorology and then "mass fluxes".

There are no corresponding `HEMCO_Config.rc` lines for these since they are not masked or scaled by HEMCO. The columns of `HEMCO_Config.rc` that specify I/O information, e.g. file path and read frequency, are ignored by GCHP since MAPL handles I/O.

Please let us know if this still does not make sense.

**Comment by deepangsu** [comment]
Hi @lizziel, Thank you for your response. 

This clarifies things in terms of cubed-sphere meteorology input. However, I was actually requesting for an "ExtData.rc" and "HEMCO_Config.rc" example that show the format for the cubed sphere emissions and associated scaling factors. 

For example here is what my HEMCO_Config.rc looks like when using emissions in LAT_LON

******************************************************************************************************************************

0 CEDS_NO_AGR     $ROOT/CEDS/v2020-08/$YYYY/NO-em-total-anthro_CEDS_$YYYY.nc            NO_agr             1970-2017/1-12/1/0 C xy kg/m2/s NO    25/18199     1 5
 
18199 IFDMB_NO     /storage1/fs1/rvmartin/Active/deepangsuchatterjee/GCHP_Global_2019/Synthetic_C90_scalor_2.nc           sc          2019/1/1/0 C xy 1 1

The identifier 18199 is used to scale the CEDS_NO_AGR emissions. 

*****************************************************************************************************************************
Here is what my ExtData.rc looks like when using emissions in LAT_LON

CEDS_NO_AGR  kg/m2/s N Y F%y4-%m2-01T00:00:00 none none NO_agr  ./HcoDir/CEDS/v2020-08/%y4/NO-em-total-anthro_CEDS_%y4.nc

IFDMB_NO 1 N Y - none none scale_factors /storage1/fs1/rvmartin/Active/deepangsuchatterjee/GCHP_Global_2019/Synthetic_C90_scalor2.nc

****************************************************************************************************************************
The Above code work fine. But now I want to do the same thing (scale emissions using scale factors) using cubed sphere emissions and cubed sphere scale factors (rest everything should remain same).

Can you just show me using the same example I shared above, how should the formatting change (for both HEMCO_Config.rc and ExtData.rc) if I want to have the same outcome using cubed sphere emissions and cubed sphere scale factors. 

I have attached the ExtData.rc and HEMCO_Config.rc file here for your reference. 

[ExtData.rc.txt](https://github.com/geoschem/GCHP/files/12255892/ExtData.rc.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/GCHP/files/12255894/HEMCO_Config.rc.txt)

**Comment by lizziel** [comment]
Hi @deepangsu, have you tried simply replacing the filenames in ExtData.rc with the filenames for the cubed-sphere versions? For your example, both the CEDS file and the scale factors file will be regridded to your run resolution, and the regridded values will be used later in HEMCO for the scaling. Whether you input as lat-lon or cubed-sphere will not make a difference because both will be regridded to your run resolution prior to the scaling. Does that make sense?

**Comment by lizziel** [comment]
I am also tagging @deepangsu and @yidant on this issue since they are our GCST members at WashU and may be abe to help more directly.

**Comment by yantosca** [comment]
Also tagging @SaptSinha

**Comment by lizziel** [comment]
Thanks @yantosca, that is who I meant to tag!

**Comment by SaptSinha** [comment]
Hello folks, @deepangsu reached out earlier to me regarding this issue and I recommended contacting the entire GCST instead.

**Comment by deepangsu** [comment]
@lizziel Thank you for your suggestion. I will try out using the cuded sphere emissions with the same format and get back to you.

**Comment by deepangsu** [comment]
Hi @lizziel @SaptSinha @yidant, So, when I am using the LAT-LON scale factors, GCHP seems to works fine. But when I am using Cubed Sphere scale factors, GCPH crashes with segmetation error. Here are the HEMCO_Config.rc, ExtData.rc and runlog.txt files for your reference. 
[HEMCO_Config.rc.txt](https://github.com/geoschem/GCHP/files/12363577/HEMCO_Config.rc.txt)

[ExtData.rc.txt](https://github.com/geoschem/GCHP/files/12363365/ExtData.rc.txt)
m/GCHP/files/12363361/HEMCO_Config.rc.txt)

[runlog.txt](https://github.com/geoschem/GCHP/files/12363373/runlog.txt)

I am also sharing the Scalor_Trail.nc (the scalors files that I am trying to use) in the box folder, for your reference. 

[https://wustl.box.com/s/nz79bwb6t58l38grht1wjncuqqf3rnqv]

**Comment by deepangsu** [comment]
Also to add, for the GEOS-FP Native input I found the line:

MFXC;MFYC Pa_m+2_s-1    N H F0;003000 none  0.6666666 MFXC;MFYC  ./MetDir/../../GEOS_C720/GEOS_FP_Native/Y%y4/M%m2/D%d2/GEOS.fp.asm.tavg_1hr_ctm_c0720_v72.%y4%m2%d2_%h2%n2.V01.nc4 2021-03-11T00:30:00P01:00

that ends with < 2021-03-11T00:30:00P01:00 >, which is absent in the GCHP LAT_LON met fields. Could you please explain the meaning of this part ? Do my input emissions (cubed spehre scale factors) need something similar in the end ?

**Comment by lizziel** [comment]
Hi @deepangsu, the extra part of the line containing a date is used when the time of the file has an offset from midnight. For this particular case of hourly data the file contains data at the mid-point per hour rather than on the hour.  The string 2021-03-11T00:30:00P01:00 is saying to read every hour starting on March 11, 2021 at 00:30:00. The month/day/year does not actually matter for this case since there are an even number of hours per day, as long as the day is on or precedes the start of the simulation. I think we do not use this method for the lat-lon data because those are stored in daily rather than hourly files, although I am not 100% sure on that.

Before I left for GCE2 and vacation I tried using your scale factors file. The issue is the file itself which I can get back to debugging this week. The problem is MAPL ExtData and not HEMCO. I suspect something in the attributes or dimensions is not exactly what MAPL expects.

**Comment by deepangsu** [comment]
Hi @lizziel Thank you for your response. I will look forward to your message for resolving the issue with the scale factors file.

**Comment by lizziel** [comment]
Hi @deepangsu, the error is happening when creating the time metadata from the time entry in your file. I suspect it does not like this format for units: `minutes since 2019-07-01T13:00:00`. Try removing the `T`. There may be other problems as well after this fix if there are additional discrepancies between metadata in your file and the standard COARDS-compliant metadata. I suggest taking a close look at other input files to make sure your file has the proper entries.

**Comment by yantosca** [comment]
Thanks @llzziel.  Yes, I think for COARDS/CF compliance the time:units cannot be in e.g. Python datetime notation (with the T).  See: https://ferret.pmel.noaa.gov/Ferret/documentation/coards-netcdf-conventions and search for "Time dimension".

**Comment by lizziel** [comment]
I will close this issue. @deepangsu, please open a new issue about reading in the file if you still have problems.

**Comment by deepangsu** [comment]
@lizziel @yantosca Thank you for your suggestions.
