### ISSUE TITLE
Small numerical error in mass flux regridding

### ISSUE THREAD

**Issue by sdeastham** [geoschem/gchp#377]
### Name and Institution (Required)

Name: Seb Eastham
Institution: Imperial College London

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [x] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question

There is a small bug in the algorithm used to handle regridding of mass fluxes between resolutions, where an edge length multiplication is missing (see https://github.com/GEOS-ESM/MAPL/issues/1199). This error is resolved by some work done by Tom Clune in https://github.com/GEOS-ESM/MAPL/pull/2056 (partially described in https://github.com/GEOS-ESM/MAPL/pull/1202).

**Comment by lizziel** [comment]
I implemented the changes in https://github.com/GEOS-ESM/MAPL/pull/2056 and compared before and after using GEOS-FP mass fluxes. The result is no differences in diagnostics and restart files.

**Comment by lizziel** [comment]
I revisited this after discussion with Tom Clune at GMAO. I pared down the updates in [https://github.com/GEOS-ESM/MAPL/pull/2056](https://github.com/GEOS-ESM/MAPL/pull/2056) to only what we need and tried again. I now see differences, although I suspect the issue before what error on my part in putting in the update.

Here is an example of differences in daily mean after a 1-day run.

<img width="1103" alt="Screen Shot 2024-06-17 at 3 31 26 PM" src="https://github.com/geoschem/GCHP/assets/651947/e5f05b4b-0c9a-447e-812d-414c80aa9660">

This update can go into 14.4.1 and I will create a PR.

**Comment by lizziel** [comment]
See MAPL PR https://github.com/geoschem/MAPL/pull/36 for this update.

**Comment by lizziel** [comment]
Now merged.

**Comment by yuanjianz** [comment]
Hi @lizziel and @sdeastham, I doubt this fixed horizontal flux regridder cannot be applied to MFXC and MFYC from GEOS. 

This bugfix itself is correct for fluxes weighted by area (in forms like kg/m2/s) as the edge length multiplication would prevent fluxes from growing bigger at coarser resolution. However, GEOS-5 MFXC and MFYC have units of Pa m2/s:

![image](https://github.com/user-attachments/assets/529ba9ab-50c4-4a52-a14a-737d034ee554)
[GEOS-5 filespec](https://gmao.gsfc.nasa.gov/GMAO_products/documents/GEOS-5_Filespec_Glossary.pdf)

As in definition, they are already multiplied by distance and grid-size aware. So `MF12 = F12 * d12 = F1 * d1 + F2 * d2 = MF1 + MF2`. Here F are area weighted fluxes and MF are "fluxes" for MFXC and MFYC. 

However, CX and CY are  `(ut or vt) * dt / (dx or dy)`. Their regridding should be multiplied by edge length to avoid unreal CX and CY at coarse grid. An example is that before the fix, coarse resolution mass flux runs using CX and CY from raw files would trigger large-n_split warning due to large CFL numbers.

In FV3 transport, there are two types of input fluxes: `xfx` and `mfx`.
```Fortran
xfx(i,j,k) = cx(i,j,k)*dxa(i-1,j)*dy(i,j)*sin_sg(i-1,j,3)
...
ra_x(i,j) = area(i,j) + (xfx(i,j,k) - xfx(i+1,j,k))
```
Fluxes `xfx` and `yfx` are used to determine grid-stretching (I guess?). They are calculated from `cx` and `cy` by multiplying grid edge length.

```Fortran
dp2(i,j) = dp1(i,j,k) + ((mfx(i,j,k)-mfx(i+1,j,k))+(mfy(i,j,k)-mfy(i,j+1,k)))*rarea(i,j)
```
`mfx` and `mfy` are directedly used to determine pressure level change and drives tracer advection.

I would say it might be necessary to keep "unfixed" and "fixed" H-regridder for `MFXC` and `CX` separately. Hope this can help explain our discussion in #342.
