### ISSUE TITLE
HEMCO CS flag for skipping new tracer species in restart file not working in GCHP, worked previously in Classic

### ISSUE THREAD

**Issue by amy1916** [geoschem/gchp#388]
### Name and Institution (Required)

Name: Amy Lees
Institution: Wolfson Atmospheric Chemistry Labs, University of York

### Confirm you have reviewed the following documentation

- [ x ] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [ x ] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ x ] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ x ] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GCHP version number and any relevant configuration and log files.

Hi, I am using GCHP v14.2.3 (with the addition of the fix for KPP integration failures https://github.com/geoschem/geos-chem/pull/2006) for a C48 simulation where I have added new dummy tracer species into the mechanism using KPP. 

I have previously done an equivalent 4x5 simulation in GEOS-Chem classic v14.2.2, and just changed the SPC_ flag in HEMCO_Config.rc to CS to allow the model to skip looking for these species that don't currently exist in the restart file and use the background concentration instead. However, adding this flag doesn't appear to work in GCHP and my simulation is still failing due to the "<Could not find field SPC_*Tracername* in gchp_restart.nc4  >" error.

My colleague who has done a similar tagged simulation, adds new species fields to the restart file. I am happy to this use as a workaround but would like clarification if the inability to use the CS flag is intended and the standard way should be to add new species to the restart file manually rather than use the background concentration? And just to make you aware that using CS flag seemed to work fine in Classic but not GCHP.  It would be great if the standard method to deal with this restart file issue was documented in the readthedocs. 

Attached is my GCHP log file. 

Thanks in advance for any clarification on this. 

[GCHP_budget_3717119.log](https://github.com/geoschem/GCHP/files/14460326/GCHP_budget_3717119.log)

**Comment by lizziel** [comment]
Hi @amy1916, thanks for reaching out about this. Some of the GEOS-Chem simulations require that all species be in the restart file, including the standard simulation. This was a new feature added recently per request of the GEOS-Chem Steering Committee to match the behavior of GEOS-Chem Classic. For GEOS-Chem Classic you can get around this by updating a flag in `HEMCO_Config.rc`, as you did. In GCHP that part of `HEMCO_Config.rc` is not used because the NASA MAPL library is used for data read instead. To configure your run to allow missing species in the restart file you instead need to flip a switch in config file `setCommonRunSettings.sh`. Search for string "Require_Species_in_Restart" in the file. If set to 1 it will require species, and if set to 0 it will not.

This question has come up a lot so I think we need to update our docs to be more clear about it. In the next version I will move the setting to higher in the config file so it is more visible. I will also update the GCHP Debugging page to specifically mention this issue to look for and how to fix it. We have [this section](https://gchp.readthedocs.io/en/stable/user-guide/rundir-config.html#enable-restart-file-to-have-missing-species) of GCHP ReadTheDocs about this. Let me know if you have ideas beyond what I just listed to make it more clear.

**Comment by amy1916** [comment]
Hi @lizziel, thank you for the clarification. Sorry, I missed that in the GCHP ReadTheDocs, I was mainly looking at the 'Update chemical mechanisms with KPP' section. I think this is clear and will be great for the setting to be more visible in the config file. Thanks again for your help with this.
