### ISSUE TITLE
[DISCUSSION] Rethink GCHP multirun option

### ISSUE THREAD

**Issue by msulprizio** [geoschem/GCHP#77]
The GCHP multi-run option (via `gchp.multirun.run` and `gchp.multirun.sh`) is currently written for SLURM schedulers. It also only works properly with monthly runs, assuming the user wants to save out monthly mean diagnostics. We should make this option more flexible and/or provide step-by-step instructions for users to automate their own multi-segmented runs.

See http://wiki.seas.harvard.edu/geos-chem/index.php/Running_GCHP:_Configuration_v12#Split_a_Simulation_Into_Multiple_Jobs

**Comment by lizziel** [comment]
The multirun should work with any duration runs. I regularly used it to do consecutive hourly runs to get quick results in diagnosing multi vs single run differences. If it only works with monthly then there must be a bug.

**Comment by msulprizio** [comment]
Perhaps the multirun option works for simulations shorter than monthly in that case. For the 1-year GCHP benchmarks, I found that running yearly simulations with the multirun scripts and selecting monthly mean diagnostics resulted in the use of `7440000` (i.e. number of hours in a 31-day month) for the duration and frequency in HISTORY.rc for all months.

**Comment by lizziel** [comment]
By yearly simulation, do you mean you programmed the duration to be one year but turned on monthly diagnostics? If yes, that is the problem. The monthly diagnostics option requires duration of exactly one month. The frequency and duration in HISTORY.rc remain constant for an entire run (MAPL limitation) so saving out mean across variable number of days is not possible otherwise.

Monthly mean should be an option in MAPL very soon, if not already in the most recent release. A first pass was done by GMAO in the fall but needed some additional MAPL work before support in GCHP. Once that is included and validated, the monthly diagnostic option can be retired which hopefully would make things less confusing.

**Comment by msulprizio** [comment]
>By yearly simulation, do you mean you programmed the duration to be one year but turned on monthly diagnostics? If yes, that is the problem. 

Yes, that is what I mean. That is typically how TransportTracer simulations are submitted. Those simulations run fast (~50 min per month on 48 CPUs) so there isn't usually a need to break them up into monthly simulations. The issue was that the documentation for the multirun option didn't clearly specify that you should not run longer than monthly segments when saving out monthly diagnostics so we should make this more clear in the script comments and/or in the online documentation. 

In general, I opened this issue to discuss make the multirun option more flexible for other simulation durations and other systems. Retiring the monthly diagnostic option would certainly help address the simulation duration problem. However, I'm told by @sdeastham and @LiamBindle that they do not use the multirun scripts provided by GCHP but rather end up writing their own scripts to run multi-segmented GCHP simulations on their systems. If we could generalize this option and/or provide instructions for users to create scripts on their own systems, I think that would be extremely helpful for all.

**Comment by lizziel** [comment]
@sdeastham and @LiamBindle, could you chime in on what your scripts to run multi-segmented GCHP simulations contain? Maybe we can converge on a recommendation for users.

Regarding monthly diagnostics, there are two issues with the `History` monthly average option that makes me hesitant to retire our use of running consecutive 1-month run jobs just yet:
1. There is a bug in the `time_increment` attribute that specifies the wrong duration for the file. See my open MAPL issue on this: https://github.com/GEOS-ESM/MAPL/issues/784
2. The files are timestamped with the start of the run in the filename. This will make our files incompatible with benchmark scripts in GCPy. An easy work-around is to rename the files for benchmarking but that is not ideal. It is also confusing that History time-averaged output can have either start and mid-point in its filename depending on if you set `collection.monthly` to 0 or 1.

**Comment by LiamBindle** [comment]
Sure thing. I usually create a run script that fills `cap_restart` with the timestamp and `GCHP.rc` with the latest `gcchem*` file. Here is an example of a script I use: https://gchp.readthedocs.io/en/latest/_downloads/aeeea62ef5e1cca66ad3870f20f8516d/c360_requeuing.sh (this is what I use for C360 which runs 7-day segments). 

For monthly diagnostics, I always output daily files and then average them together in post processing.

I would lean towards recomending users handle multi-segment runs in their own run scripts because schedulers, environments, and use cases are so diverse. I think a couple small scripts in the `utils/` subdirectory could be helpful for this, e.g., updating `cap_restart` timestamp and `GCHP.rc` according to the latest `gcchem*` file, or updating frequencies and durations in `HISTORY.rc`.

**Comment by sdeastham** [comment]
My workflow is similar. I list `GCHP_restart.nc` as the restart in `runConfig.sh`, then modify `gchp.run` to make use of `cap_restart`, usually having something like:

```
# Get resolution
CS_RES=$( grep '^CS_RES=' runConfig.sh | cut -d'=' -f 2 )

# Set up next run
if [[ -L GCHP_restart.nc ]]; then
   unlink GCHP_restart.nc
fi
# Check that cap_restart exists and is not empty
if [[ -s cap_restart ]]; then
   restart_datetime=$(echo $(cat cap_restart) | sed 's/ /_/g')
   ln -s OutputDir/gcchem_internal_checkpoint.restart.${restart_datetime}.nc4 GCHP_restart.nc
else
   ln -s $( readlink -f initial_GEOSChem_rst.c${CS_RES}_fullchem.nc ) GCHP_restart.nc
fi
```

I also get monthly output by averaging. Generally I'd agree that it's best to have the users handle multi-segment runs using the MAPL approach, although I also do like having examples available for common schedulers.

On a similar note, I should mention that I find myself tripping over the automated `HISTORY.rc` frequency setting behavior, but that's because I'm usually building my own diagnostic archives (and forget when I add in one of the standard ones that it will get hit by `runConfig.sh`).

**Comment by LiamBindle** [comment]
I also usually build my own diagnostic archives. I usually modify the frequency and duration settings manually.

**Comment by lizziel** [comment]
Re: multirun scripts

I vote for having a few simple examples but leave it to the user to customize their own scripts. The important thing is communicating the behavior of `cap_restart` and checkpoint files to avoid pitfalls. Fortunately it just got easier with the presence of `gcchem_internal_checkpoint` in the run directory no longer causing a crash in MAPL (starting in GCHP 13.1). Scripts and docs need to updated accordingly.

Re: `runConfig.sh`

I've also run into this problem with the automated `frequency`/`duration` settings and know at least one student who has as well. Rather than remove it, what do you think of an on/off toggle to set ALL collections to the same dur/freq, with the default being same as simulation period? This would prevent new diagnostics from being excluded, better allow customization, and still keep the convenience functionality as an option.

The goal of the run config script is to avoid mistakes that come with having to configure multiple files. But we don't want it to get heavy-handed. Are we starting to reach that point? The file is bloated with settings, instructional comments, and execution code. It's all in one place to make it simple for any user to understand what is happening under the hood. But maybe having a settings, instructions, and execution code separated would be easy to use and understand too?

Re: monthly diagnostics

We are expecting a MAPL History fix from GMAO for the `time_increment` field in the monthly collection files. I verified the data in the monthly files are correct so this is the only remaining bug. If you don't mind the filename including start rather than mid-point you can start using this in 13.1 rather than do post-processing from daily files. I have a feature request for our benchmark scripts to use either start or mid-point in GCHP filenames to allow using either (for backwards compatibility and adaptability for non-month file comparisons). Once that's there I think we can discontinue using the monthly diagnostic functionality of my multirun script in benchmarks and remove the option from `runConfig.sh`.

**Comment by lizziel** [comment]
Following up on this, I carried out the plan I outlined above to remove the multi-run option from `runConfig.sh` in 13.1 when the monthly diagnostics became available. I left the multi-run scripts in the Harvard folder for run scripts but they may need editing - @msulprizio found that they still expect the number of runs from `runConfig.sh`.

Should we remove the multi-run scripts from the repo and keep custom run scripts for benchmarking locally for our own use, or keep them there as an example but update so functional?

**Comment by msulprizio** [comment]
BTW, I was able to restore the existing multi-run functionality (using scripts `run/runScriptSamples/operational_examples/harvard_gcst/gchp.multirun*`) by adding the NUM_RUNS and MONTHLY_DIAG options back to `runConfig.sh`:

```
#------------------------------------------------
#    Simulation start, end, duration
#------------------------------------------------
Start_Time="20180701 000000"
End_Time="20200101 000000"
Duration="00000100 000000"
Num_Runs=18    # Only for use with multi-run script gchp.multirun.sh
Monthly_Diag=1 # Only for use with multi-run script gchp.multirun.sh. Set to 1 to enable.
```

Alternatively, we could move these variables to the `gchp.multirun*` example scripts so as not to confuse users with their presence in `runConfig.sh`. I think this option would make more sense because this is a feature used by the GCST at Harvard for benchmarking purposes and may not necessarily want to used by all. As pointed out above, other users have different methods and scripts for performing multi-segmented runs.

**Comment by lizziel** [comment]
I would prefer those variables not be in `runConfig.sh` since it then looks like this is a supported option. I think the multi-run scripts are too customized to support for all users. Plus we still have differences between multi and single segmented runs so doing longer runs rather than monthly runs is preferred.

@sdeastham, please note that I was incorrect before in my statements that once we have monthly time-averaged diagnostics in history we would no longer split up GCHP runs into 1-month segments for benchmarking. We may continue to do this, for GC-Classic too.

**Comment by lizziel** [comment]
Following up on this issue, we are keeping the GCHP multi-run scripts in the geos-chem repo for use by GCST and to provide an example to the community of one way of doing multiple consecutive runs. The scripts are in the Harvard folder of run script examples and are not meant for direct use by the community - they would need to be adapted and serve only as an example of something that works on the Harvard cluster. We have no plans to further change the scripts in the future or create more generic multi-run scripts to distribute to the community, so I will now close out this discussion.
